-- Fixed art direction and performance limits; no asset uploads required.
return {
    max_active = 8,
    ring_segments = 48,
    ring_thickness = 0.07,
    ground_lift = 0.06,
    surface_transparency = 0.12,
    material = "SmoothPlastic",
    core_material = "Neon",
    core_width = 0.28,
    core_height = 0.86,
    tip_fraction = 0.78,
    minimum_size = 0.001,
    height_min = 0.45,
    height_variation = 0.55,
    center_boost = 0.65,
    width_min = 0.7,
    width_variation = 0.6,
    angle_jitter = 0.24,
    ring_start = 0.25,
    ring_lifetime = 0.65,
    ring_opacity = 0.85,
    spark_size = 0.12,
    spark_lifetime = 0.9,
    spark_speed = 12,
    spark_gravity = 20,
    ray_height = 20,
    ray_depth = 80,
}
