--[[
    build_info — GENERATED by scripts/stamp_build.sh (mise run stamp). Do NOT
    hand-edit: it's overwritten on every build/publish. Shows on the BootLoader
    load screen so a published build is identifiable at a glance. While Rojo is
    served through mise, the stamp watcher refreshes this whenever HEAD or the
    working tree changes. Times are Mountain (America/Denver, DST-correct).
]]
return {
    version = "0.3.0",
    commit = "a2ab9a2f",
    branch = "main",
    commit_date = "2026-09-04 04:04 PM MDT", -- when the running code was committed
    built_at = "2026-09-04 04:05 PM MDT", -- when this build was stamped (publish time)
    dirty = false, -- uncommitted changes present at stamp time
}
