-- Course boundaries reference the canonical combat_tutorial lesson catalog.
return {
    version = 1,
    replay_completion = {
        localization_key = "combat_courses.replay.completion",
        title = "REPLAY COMPLETE",
        body = "Welcome back! This course's one-time reward was already earned.",
        show_seconds = 8,
    },
    level_cap = 50,
    analytics = {
        enabled = true,
        suffix = " v1",
        entry_name = "Entered course",
        finish_name = "Completed course",
    },
    finish_pillar = {
        title = "Complete this course",
        body = "The room is clear. Activate the glowing pillar to receive your reward and return to the game.",
    },
    menu = {
        title = "Combat Training",
        body = "Basic unlocks pets. Advanced courses are optional. Each course awards one earned level (up to 50), once. Replays have no completion reward.",
        cancel = "Not now",
        start = "Start",
        resume = "Resume",
        replay = "Replay",
        locked = "Finish the previous course",
        layout = {
            width = 0.58,
            height = 0.52,
            row_top = 0.38,
            row_height = 0.13,
            row_gap = 0.02,
            min_text = 12,
            max_text = 24,
        },
    },
    courses = {
        {
            id = "basic",
            key = "CombatTutorial",
            title = "Basic Combat Training",
            first = "ready",
            last = "advance_heal",
            completion = {
                apply_level_grant = true,
                grant_levels = 1,
                title = "BASIC COMPLETE — PETS UNLOCKED!",
                body = "Pets and powers are unlocked. You earned a level (up to 50). Advanced training is optional.",
                banner = "Basic Combat Training complete — pets unlocked!",
                show_seconds = 8,
                grant = {
                    currencies = { grass_coins = 250 },
                    potions = {
                        { id = "berserk_brew", count = 3 },
                        { id = "weakening_vial", count = 2 },
                    },
                },
            },
        },
        {
            id = "advanced_1",
            key = "CombatTutorialAdvanced1",
            title = "Advanced 1",
            first = "ready_weaken",
            last = "advance_stack",
            prerequisite = "CombatTutorial",
            completion = {
                apply_level_grant = true,
                grant_levels = 1,
                title = "ADVANCED 1 COMPLETE!",
                body = "One earned level (up to 50) and a Double XP token. Activate the token from your inventory when you want it.",
                banner = "Advanced 1 complete — Double XP token earned!",
                show_seconds = 8,
                grant = { items = { { id = "double_xp_token", qty = 1, bucket = "consumables" } } },
            },
        },
        {
            id = "advanced_2",
            key = "CombatTutorialAdvanced2",
            title = "Advanced 2",
            first = "ready_tank",
            last = "advance_together",
            prerequisite = "CombatTutorialAdvanced1",
            completion = {
                apply_level_grant = true,
                grant_levels = 1,
                title = "ADVANCED 2 COMPLETE!",
                body = "One earned level (up to 50) and a Double Coins token. Activate the token from your inventory when you want it.",
                banner = "Advanced 2 complete — Double Coins token earned!",
                show_seconds = 8,
                grant = {
                    items = { { id = "double_coins_token", qty = 1, bucket = "consumables" } },
                },
            },
        },
    },
}
