-- Crossroads arena content and tuning. Authored CombatBounds is the outer floor footprint.
return {
    enabled = true,
    studio_rewards = false,
    bounds_path = { "RealmCrossroadsR4", "CrossroadsActivitiesR7", "PatrolGrove", "CombatBounds" },
    floor_path = { "RealmCrossroadsR4", "CrossroadsActivitiesR7", "PatrolGrove", "Playfield" },
    poll_seconds = 0.5,
    arrival_seconds = 2,
    entry_audio = {
        id = "rbxassetid://85508116459916",
        volume = 0.5,
        seconds = 5.88,
        cleanup_tail = 0.75,
        cooldown_seconds = 8,
        cue_attribute = "CrossroadsArenaEntryCue",
    },
    round_pause_seconds = 12,
    abandoned_seconds = 8,
    max_round_seconds = 600,
    seed_max = 2147483646,
    axis_tolerance = 0.999,
    entry_inset = 1,
    enemy_inset = 3,
    participant_height = 40,
    participant_below_floor = 4,
    spawn_height = 3,
    max_enemies = 24,
    spawn_grid = { columns = 4, rows = 6, spacing = 9 },
    rank_tiers = {
        minion = "trash_mob",
        lieutenant = "mid_tier",
        boss = "boss",
        titan = "archvillain",
    },
    -- Early squads use the same rank pipeline at a gentler HP/damage/ability scale.
    onramp = { min_level = 1, max_level = 14, min_hp_mult = 0.3, min_damage_mult = 0.25 },
    teams = {
        {
            min_level = 1,
            max_level = 4,
            name = "Woodland Challengers",
            egg_mission = "heaven_trial",
            packs = {
                {
                    weight = 1,
                    boss = true,
                    units = {
                        { pet = "doggy", rank = "minion", count = 2 },
                        { pet = "kitty", rank = "minion", count = 1 },
                        { pet = "bear", rank = "boss", count = 1 },
                    },
                },
            },
        },
        {
            min_level = 5,
            max_level = 50,
            name = "Frostlight Challengers",
            egg_mission = "heaven_trial",
            packs = {
                {
                    weight = 1,
                    boss = true,
                    units = {
                        { pet = "frostlight_doe", rank = "minion", count = 2 },
                        { pet = "prism_fox", rank = "minion", count = 1 },
                        { pet = "starlight_owl", rank = "lieutenant", count = 1 },
                        { pet = "glacial_bear", rank = "boss", count = 1 },
                    },
                },
            },
        },
        {
            min_level = 5,
            max_level = 50,
            name = "Blight Challengers",
            egg_mission = "hell_trial",
            packs = {
                {
                    weight = 1,
                    boss = true,
                    units = {
                        { pet = "dread_hare", rank = "minion", count = 2 },
                        { pet = "cinderling_imp", rank = "minion", count = 1 },
                        { pet = "dread_owl", rank = "lieutenant", count = 1 },
                        { pet = "rotleaf_stag", rank = "boss", count = 1 },
                    },
                },
            },
        },
    },
    arrival_fx = {
        enabled = true,
        distance = 220,
        late_seconds = 2,
        height = 38,
        runtime_name = "CrossroadsArenaArrivals",
        poll_seconds = 0.1,
        reduced_motion_attribute = "CrossroadsReducedMotion",
        thunder = {
            id = "rbxassetid://123407646075746",
            volume = 0.5,
            seconds = 8.49,
        },
        lightning = {
            enabled = true,
            duration = 0.55,
            segments = 12,
            core_enabled = false,
            thickness = 0.16,
            strands_per_origin = 1,
            origin_limit = 1,
            center_flash = true,
            sound_name = "",
            volume = 0,
            colors = { { 130, 205, 255 }, { 230, 240, 255 } },
        },
    },
}
