-- Shared host assignments and movement; all personality copy is in crossroads_host_lines.
local areas = require(script.Parent.areas).crossroads
local arena = require(script.Parent.crossroads_arena)
local garden = require(script.Parent.crossroads_garden)
local merge = require(script.Parent.merge_egg_prototype).gate.crossroads_entry
return {
    enabled = true,
    poll_seconds = 0.25,
    normal_speed = 22,
    rush_speed = 60,
    minimum_travel_seconds = 0.3,
    maximum_travel_seconds = 7,
    position_threshold = 1,
    look_threshold = 5,
    gate_enter_radius = 26,
    gate_exit_radius = 34,
    gate_service_seconds = 35,
    activity_approach_radius = 22,
    activity_exit_radius = 32,
    egg_enter_radius = 22,
    vertical_range = 28,
    hearing_radius = 90,
    minimum_hearing_distance = 15,
    comment_interval_seconds = 25,
    reaction_interval_seconds = 10,
    reaction_expiry_seconds = 25,
    max_activity_lines_per_visit = 6,
    arena_entry_voice_grace_seconds = 7,
    group_name = "CrossroadsHosts",
    hosts = {
        angel = {
            face_path = { areas.root_name, "ExistingMergeArches", "FarmAndFight", "Face" },
            gate_path = { areas.root_name, table.unpack(areas.gate_path) },
            activity = "garden",
            activity_path = { table.unpack(garden.root_path) },
            activity_part = garden.field_name,
            egg_part = garden.anchor_name,
            watch_offset = { 42, 10, 0 },
            egg_offset = { 12, 3, 8 },
            greeting = { "hosts.angel.greeting", "hosts.angel.advice" },
            return_cue = "hosts.angel.return",
            approach_cue = "hosts.angel.garden",
            egg_cue = "hosts.angel.egg",
            hatch_cue = "hosts.angel.hatched",
            comments = { "hosts.angel.working1", "hosts.angel.working2" },
        },
        demon = {
            face_path = { areas.root_name, "ExistingMergeArches", "Merge", "Face" },
            gate_path = { merge.root_name, table.unpack(merge.path) },
            activity = "arena",
            activity_path = arena.bounds_path,
            watch_offset = { -42, 8, 0 },
            greeting = { "hosts.demon.greeting", "hosts.demon.advice" },
            return_cue = "hosts.demon.return",
            approach_cue = "hosts.demon.arena",
            comments = { "hosts.demon.fighting1", "hosts.demon.fighting2", "hosts.demon.fighting3" },
            defeated_cue = "hosts.demon.defeated",
            victory_cue = "hosts.demon.victory",
            retreat_cue = "hosts.demon.retreat",
        },
    },
}
