-- One edit selects the pavilion egg; prices and coin presentation live here too.
return {
    enabled = true,
    root_path = { "RealmCrossroadsR4", "CrossroadsActivitiesR7", "CoinGarden" },
    field_name = "CoinDropField",
    floor_name = "Playfield",
    stand_name = "hall_egg_stand",
    anchor_name = "WeeklyEggAnchor",
    preview_name = "wayfinder_egg",
    egg = { id = "crossroads_featured_egg", source = "wayfinder_egg", cost = 100, height = 5 },
    currency = {
        id = "crossroads_coins",
        name = "Crossroad Coins",
        description = "Silver coins collected in Crossroads and spent at its featured egg.",
        maxAmount = 999999999,
        defaultAmount = 0,
        icon = "C",
        icon_asset = "rbxassetid://118811944830895",
        tradeable = false,
    },
    pickup = {
        mesh = "rbxassetid://84405380672213",
        texture = "rbxassetid://85165485647097",
        color = { 255, 255, 255 },
        material = "SmoothPlastic",
        reflectance = 0,
        size = 1.6,
        orientation = { x = 0, y = 0, z = 0 },
    },
    hud = {
        fill = Color3.fromRGB(92, 103, 121),
        light = Color3.fromRGB(217, 229, 242),
        gem = Color3.fromRGB(188, 202, 220),
        symbol = "C",
    },
    world = "CrossroadsGarden",
    mining_area = "Spawn",
    chest = {
        asset_id = "rbxassetid://127175449944140",
        texture_asset = "rbxassetid://125784646482090",
        -- Imported FBX carries a -90-degree pitch; restore the lid-up orientation.
        default_orientation = { x = 90, y = 0, z = 0 },
        normalize_prebaked_orientation = true,
        normalize_part_pivots = true,
        spawn = { method = "drop", height = 20, duration = 0.9 },
        placement = { height_offset = 0, sink_depth = 0, embed_ratio = 0 },
        physics = { anchored = true, can_collide = false, can_touch = false, can_query = true },
    },
    targets = {
        {
            id = "CrossroadChest",
            display_name = "Crossroad Chest",
            health = 120,
            value = 25,
            scale = 3.5,
            weight = 3,
        },
        {
            id = "CrossroadStrongbox",
            display_name = "Crossroad Strongbox",
            health = 400,
            value = 75,
            scale = 5,
            weight = 1,
        },
    },
    poll_seconds = 0.5,
    spawn_seconds = 2,
    max_targets = 12,
    nearby_radius = 100,
    vertical_range = 35,
    field_inset = 6,
    min_spacing = 12,
    placement_attempts = 10,
}
