-- Timing and catch/escape decisions are deliberately client-owned (Jason, 2026-09-09).
local coin = require(script.Parent.crossroads_garden).currency.id
return {
    enabled = true,
    root_name = "RealmCrossroadsR4",
    fishing_root = "CrossroadsFishingR10",
    station_attribute = "StationKey",
    prompt_attribute = "StubAction",
    prompt_value = "fishing_preview",
    distance = 9,
    release_distance = 14,
    command = "fishing.claim",
    receipt_limit = 24,
    input = {
        hit = Enum.KeyCode.E,
        gamepad_hit = Enum.KeyCode.ButtonX,
        cancel = Enum.KeyCode.Q,
        gamepad_cancel = Enum.KeyCode.ButtonB,
        priority = 3000,
    },
    cast = {
        seconds = 0.65,
        reel_seconds = 0.55,
        arc_height = 4,
        water_offset = 0.18,
        bob_amplitude = 0.08,
        bob_period = 2.5,
        bobber_size = Vector3.new(0.5, 0.7, 0.5),
        bobber_color = Color3.fromRGB(222, 187, 81),
        line_color = Color3.fromRGB(214, 224, 213),
        line_width = 0.025,
    },
    timing = {
        wait_min = 2.5,
        wait_max = 5,
        duration = 8,
        floor = 8,
        cap_min = 65,
        cap_max = 94,
        period_min = 1.5,
        period_max = 2.6,
        wobble = 3,
        wobble_hz = 2.8,
        surge_chance = 0.02,
        surge_duration = 0.28,
        surge_plateau = 0.08,
        surge_earliest = 1,
        surge_latest = 6.8,
        escape_at_zero = 0.72,
        escape_at_full = 0.02,
        result_seconds = 3,
        network_timeout = 12,
    },
    ui = {
        position = UDim2.fromScale(0.5, 0.67),
        size = UDim2.fromScale(0.86, 0.23),
        minimum = Vector2.new(280, 170),
        maximum = Vector2.new(480, 210),
        display_order = 160,
        short_height = 500,
        short_position = UDim2.fromScale(0.5, 0.48),
        blocking_guis = { "AwardReceiptModal" },
        text_max = { title = 22, status = 18, score = 18, hit = 20, cancel = 16 },
        corner = 14,
        stroke = 2,
        panel = Color3.fromRGB(23, 33, 49),
        track = Color3.fromRGB(45, 59, 77),
        text = Color3.fromRGB(244, 249, 255),
        muted = Color3.fromRGB(185, 208, 228),
        low = Color3.fromRGB(224, 119, 91),
        high = Color3.fromRGB(72, 216, 184),
        peak = Color3.fromRGB(247, 216, 88),
        button = Color3.fromRGB(34, 116, 152),
        font = Enum.Font.GothamBold,
        layout = {
            title = { position = UDim2.fromScale(0.05, 0.04), size = UDim2.fromScale(0.9, 0.15) },
            status = { position = UDim2.fromScale(0.05, 0.2), size = UDim2.fromScale(0.9, 0.18) },
            bar = { position = UDim2.fromScale(0.05, 0.43), size = UDim2.fromScale(0.9, 0.14) },
            score = { position = UDim2.fromScale(0.05, 0.42), size = UDim2.fromScale(0.9, 0.16) },
            hit = { position = UDim2.fromScale(0.05, 0.65), size = UDim2.fromScale(0.58, 0.29) },
            cancel = { position = UDim2.fromScale(0.66, 0.65), size = UDim2.fromScale(0.29, 0.29) },
        },
        title = "FISHING",
        cast = "Cast line",
        object = "Fishing",
        casting = "Casting…",
        waiting = "Wait for a bite…",
        bite = "BITE! Stop at high luck • %ds",
        luck = "Luck %d%%",
        hit = "HOOK",
        cancel = "CANCEL",
        reeling = "Reeling in…",
        lost = "It slipped away!",
        timeout = "The fish got away.",
        pending = "Landing your catch…",
        failed = "Catch could not be saved. Try again.",
        success = "%s • %s",
        tiers = { "Modest catch", "Good catch", "Great catch", "Exceptional catch" },
    },
    -- Rewards are shared existing inventory/currency types, not a second fish inventory.
    tiers = {
        {
            minimum = 0,
            rewards = {
                {
                    weight = 1,
                    label = "20 Crossroad Coins",
                    bundle = { currencies = { [coin] = 20 } },
                },
            },
        },
        {
            minimum = 40,
            rewards = {
                {
                    weight = 8,
                    label = "50 Crossroad Coins",
                    bundle = { currencies = { [coin] = 50 } },
                },
                { weight = 2, label = "2 Gems", bundle = { currencies = { gems = 2 } } },
            },
        },
        {
            minimum = 70,
            rewards = {
                {
                    weight = 7,
                    label = "100 Crossroad Coins",
                    bundle = { currencies = { [coin] = 100 } },
                },
                { weight = 3, label = "5 Gems", bundle = { currencies = { gems = 5 } } },
            },
        },
        {
            minimum = 90,
            rewards = {
                {
                    weight = 5,
                    label = "200 Crossroad Coins",
                    bundle = { currencies = { [coin] = 200 } },
                },
                { weight = 5, label = "10 Gems", bundle = { currencies = { gems = 10 } } },
            },
        },
    },
}
