--[[
    Hoverboard — Hall Level-2 traversal graduation.

    One standard board for every eligible player. Traversal itself is not a
    combat power and not a second permanent-speed entitlement. Cosmetic
    recolors are Kade's shack catalog: free giveaways, gem boards, and one
    Robux board. Ownership lives in GameData.Hoverboard, not mount inventory.
]]

return {
    enabled = true,
    unlock = {
        tutorial_required = true,
        required_level = 2,
    },
    -- Floor under ordinary travel. Mounted speed is max(WalkSpeed * Eff_Speed, cruise).
    -- 64 is a skate-cruise (~4× default walk) so the Hall fields do not take a jog.
    cruise_speed = 64,
    -- Clearance from ground to the deck. HRP lift adds the usual R15 hip offset on top.
    hover_height = 3.6,
    stance_yaw_degrees = 90,
    -- Short vertical hop in place, then the board appears on the way down.
    -- jump clips are only a takeoff pose; physics owns the height.
    mount = {
        source = "animate",
        jump_height = 11,
        jump_seconds = 0.36,
        anim_speed = 2.2,
        -- Standing measure only. 0,0 is the Foot part box; no extra boot fudge.
        boot_below_box = 0,
        sole_drop = -0.7,
    },
    keybind = "H",
    -- Live-tuned 2026-08-19: mesh sits off-axis in the FBX.
    flatten = {
        pitch_degrees = 10.1,
        roll_degrees = -0.2,
    },
    -- Skate + surf keep one deck-wide wake. Rockets emit two nozzle trails.
    -- Engine offsets are fractions of half mesh size (X length, Z width, Y thick).
    ride_fx = {
        lifetime = 0.28,
        min_length = 0.2,
        deck = {
            color = { 255, 230, 160 },
            fade = { 120, 200, 220 },
            light = { 255, 220, 140 },
        },
        engines = {
            along = -0.80,
            across = 0.52,
            height = -0.12,
            width = 0.36,
            lifetime = 0.42,
        },
    },
    -- Each colorway is its own Meshy mesh + matching albedo. Meshy re-unwraps
    -- recolors, so a shared mesh + foreign atlas kaleidoscopes.
    default_skin = "black_gold",
    skins = {
        black_gold = {
            display_name = "Black Gold",
            mesh_asset = "rbxassetid://106160270625805",
            texture_asset = "rbxassetid://106362955686682",
            icon = "rbxassetid://87061483301808",
            length = 5.4,
            deck_yaw_degrees = 0,
        },
        green_white = {
            display_name = "Green White",
            mesh_asset = "rbxassetid://120196894539668",
            texture_asset = "rbxassetid://138907188850875",
            icon = "rbxassetid://112798106384374",
            length = 5.4,
            deck_yaw_degrees = 0,
        },
        orange_black = {
            display_name = "Orange Black",
            mesh_asset = "rbxassetid://81823991106177",
            texture_asset = "rbxassetid://100111684455833",
            icon = "rbxassetid://132269632223665",
            length = 5.4,
            deck_yaw_degrees = 0,
        },
        white_red = {
            display_name = "White Red",
            mesh_asset = "rbxassetid://107106683475888",
            texture_asset = "rbxassetid://80419383868895",
            icon = "rbxassetid://76324772471833",
            length = 5.4,
            deck_yaw_degrees = 0,
        },
        blue_gold = {
            display_name = "Blue Gold",
            mesh_asset = "rbxassetid://107782231692733",
            texture_asset = "rbxassetid://94992959538591",
            icon = "rbxassetid://75952704459390",
            length = 5.4,
            deck_yaw_degrees = 0,
        },
        surf_blue = {
            display_name = "Blue Surf",
            mesh_asset = "rbxassetid://100950220964401",
            texture_asset = "rbxassetid://119278352204562",
            icon = "rbxassetid://117143775561972",
            length = 12.4,
            deck_yaw_degrees = 180,
            pitch_degrees = 90,
            roll_degrees = 0.5,
            sole_drop = -0.2,
        },
        surf_green = {
            display_name = "Green Surf",
            mesh_asset = "rbxassetid://80278668372830",
            texture_asset = "rbxassetid://74765248927064",
            icon = "rbxassetid://139763699272656",
            length = 12.4,
            deck_yaw_degrees = 180,
            pitch_degrees = 90,
            roll_degrees = 0.5,
            sole_drop = -0.2,
        },
        surf_orange = {
            display_name = "Orange Surf",
            mesh_asset = "rbxassetid://109317365695389",
            texture_asset = "rbxassetid://105400480808574",
            icon = "rbxassetid://96082451486237",
            length = 12.4,
            deck_yaw_degrees = 180,
            pitch_degrees = 90,
            roll_degrees = 0.5,
            sole_drop = -0.2,
        },
        surf_purple = {
            display_name = "Purple Surf",
            mesh_asset = "rbxassetid://105874976370618",
            texture_asset = "rbxassetid://132111181151334",
            icon = "rbxassetid://101287015320374",
            length = 12.4,
            deck_yaw_degrees = 180,
            pitch_degrees = 90,
            roll_degrees = 0.5,
            sole_drop = -0.2,
        },
        surf_yellow = {
            display_name = "Yellow Surf",
            mesh_asset = "rbxassetid://88992456084036",
            texture_asset = "rbxassetid://90441648070879",
            icon = "rbxassetid://90986899452531",
            length = 12.4,
            deck_yaw_degrees = 180,
            pitch_degrees = 90,
            roll_degrees = 0.5,
            sole_drop = -0.2,
        },
        rocket_blue = {
            display_name = "Blue Rocket",
            mesh_asset = "rbxassetid://117138673433205",
            texture_asset = "rbxassetid://71787865530109",
            icon = "rbxassetid://129252383967484",
            length = 8.1,
            deck_yaw_degrees = 90,
            pitch_degrees = 0,
            roll_degrees = 0,
            sole_drop = -0.2,
            cruise_multiplier = 2,
            cruise_speed = 128,
            ride_fx = "engines",
            accent_color = { 40, 110, 255 },
        },
        rocket_lightblue = {
            display_name = "Light Blue Rocket",
            mesh_asset = "rbxassetid://76682335674258",
            texture_asset = "rbxassetid://81007461024536",
            icon = "rbxassetid://133972121715113",
            length = 8.1,
            deck_yaw_degrees = 90,
            pitch_degrees = 0,
            roll_degrees = 0,
            sole_drop = -0.2,
            cruise_multiplier = 2,
            cruise_speed = 128,
            ride_fx = "engines",
            accent_color = { 90, 200, 255 },
        },
        rocket_green = {
            display_name = "Green Rocket",
            mesh_asset = "rbxassetid://71618028846487",
            texture_asset = "rbxassetid://105398201025679",
            icon = "rbxassetid://96303282078395",
            length = 8.1,
            deck_yaw_degrees = 90,
            pitch_degrees = 0,
            roll_degrees = 0,
            sole_drop = -0.2,
            cruise_multiplier = 2,
            cruise_speed = 128,
            ride_fx = "engines",
            accent_color = { 50, 220, 90 },
        },
        rocket_orange = {
            display_name = "Orange Rocket",
            mesh_asset = "rbxassetid://101957059386544",
            texture_asset = "rbxassetid://139838111779734",
            icon = "rbxassetid://116281403293135",
            length = 8.1,
            deck_yaw_degrees = 90,
            pitch_degrees = 0,
            roll_degrees = 0,
            sole_drop = -0.2,
            cruise_multiplier = 2,
            cruise_speed = 128,
            ride_fx = "engines",
            accent_color = { 255, 118, 28 },
        },
        rocket_purple = {
            display_name = "Purple Rocket",
            mesh_asset = "rbxassetid://78046396356932",
            texture_asset = "rbxassetid://96369411448428",
            icon = "rbxassetid://100574923388292",
            length = 8.1,
            deck_yaw_degrees = 90,
            pitch_degrees = 0,
            roll_degrees = 0,
            sole_drop = -0.2,
            cruise_multiplier = 2,
            cruise_speed = 128,
            ride_fx = "engines",
            accent_color = { 170, 70, 255 },
        },
        rocket_yellow = {
            display_name = "Yellow Rocket",
            mesh_asset = "rbxassetid://110315632323608",
            texture_asset = "rbxassetid://95038196703144",
            icon = "rbxassetid://140411912611437",
            length = 8.1,
            deck_yaw_degrees = 90,
            pitch_degrees = 0,
            roll_degrees = 0,
            sole_drop = -0.2,
            cruise_multiplier = 2,
            cruise_speed = 128,
            ride_fx = "engines",
            accent_color = { 255, 220, 40 },
        },
    },
    button = {
        name = "HoverboardButton",
        text = "Board",
        icon = "rbxassetid://87061483301808",
    },
    shop = {
        enabled = true,
        npc = {
            user_id = 536245038,
            name = "Kade",
            display_name = "Kade",
        },
        location = {
            map_name = "FuturePath",
            tile_name = "Tile01_cap",
            model_name = "Shack",
            npc = { x = 1814, y = 3, z = -202, yaw_degrees = -90 },
            -- Roof-top block letters, facing the doorway (+X / Kade).
            -- Client visualization only (BlockLetterRainbow).
            sign = {
                name = "KadesBoardsSign",
                lines = { "KADE'S", "BOARDS" },
                x = 1805,
                y = 36.5,
                z = -202,
                yaw_degrees = 90,
                cell = 0.75,
                depth = 1.15,
                letter_gap = 0.75,
                line_gap = 1.5,
                color = { 255, 214, 80 },
                color_mode = "rainbow",
                -- Full hue cycle per second. 0.3 = one pass about every 3 seconds.
                rainbow_speed = 0.3,
                backing_color = { 18, 22, 16 },
                backing_transparency = 1,
                material = "Neon",
            },
        },
        interaction = {
            action_text = "Talk",
            object_text = "Kade",
            max_distance = 18,
            access_seconds = 120,
            distance_grace = 8,
        },
        -- Kade tells this when the catalog opens. Shop UI uses the keyed
        -- skin icons; no 3D board lineup outside the shack.
        story = {
            title = "Kade's Boards",
            lines = {
                'Three years I asked Colorado for hoverboards. Three years of "soon," "after the pets," "after the Hall."',
                "I wanted people to actually get around this place. He wanted another dragon.",
                "So I paid for the boards myself. A couple are on the house — take one. The fancy ones I have to charge for, or I can't keep the shack stocked.",
            },
        },
        messages = {
            insufficient_funds = "insufficient funds",
            confirm_spend = "Spend %d gems on %s?",
            confirm_button = "Spend %d gems",
            cancel_button = "Cancel",
            ok_button = "OK",
        },
        -- kind: free | gems | robux. Hoverboards are free. Surfs are gems.
        -- Rockets are Robux (product id 0 until dashboard SKUs exist; Studio
        -- test_mode grants like titan_team tokens).
        catalog = {
            black_gold = { kind = "free", price = 0, order = 1 },
            green_white = { kind = "free", price = 0, order = 2 },
            orange_black = { kind = "free", price = 0, order = 3 },
            white_red = { kind = "free", price = 0, order = 4 },
            blue_gold = { kind = "free", price = 0, order = 5 },
            surf_blue = { kind = "gems", price = 900, order = 6 },
            surf_green = { kind = "gems", price = 950, order = 7 },
            surf_orange = { kind = "gems", price = 1000, order = 8 },
            surf_purple = { kind = "gems", price = 1100, order = 9 },
            surf_yellow = { kind = "gems", price = 1050, order = 10 },
            rocket_blue = {
                kind = "robux",
                product = "hoverboard_rocket_blue",
                price_robux = 19,
                on_sale = true,
                order = 11,
            },
            rocket_lightblue = {
                kind = "robux",
                product = "hoverboard_rocket_lightblue",
                price_robux = 19,
                on_sale = true,
                order = 12,
            },
            rocket_green = {
                kind = "robux",
                product = "hoverboard_rocket_green",
                price_robux = 19,
                on_sale = true,
                order = 13,
            },
            rocket_orange = {
                kind = "robux",
                product = "hoverboard_rocket_orange",
                price_robux = 19,
                on_sale = true,
                order = 14,
            },
            rocket_purple = {
                kind = "robux",
                product = "hoverboard_rocket_purple",
                price_robux = 19,
                on_sale = true,
                order = 15,
            },
            rocket_yellow = {
                kind = "robux",
                product = "hoverboard_rocket_yellow",
                price_robux = 19,
                on_sale = true,
                order = 16,
            },
        },
    },
}
