-- Shared menu sizing and touch controls. Content stays inside device-safe bounds.
return {
    compact_height = 600,
    compact_width = 700,
    compact_panel = { width = 0.96, height = 0.96 },
    expanded_panel = { width = 0.9, height = 0.94 },
    maximum_panel = { width = 1200, height = 1000 },
    header_height = 44,
    control_height = 44,
    row_height = 54,
    row_gap = 6,
    control_font_size = 15,
    close_size = 44,
    slider_track_height = 8,
    slider_endpoint_snap_fraction = 0.03,
    slider_gamepad_step_fraction = 0.1,
    result_height = 54,
    admin_filter_placeholder = "Search this category…",
    admin_title = "Admin",
    admin_logging_result = "Client logging: %s · Console: %s · Performance: %s",
    admin_no_matches = "No matching actions in this category.",
    admin_invalid_log_level = "Use ClientModule:debug, info, warn, error, or off.",
    admin_log_level_set = "%s client logging: %s",
    admin_invalid_amount = "Enter a valid amount, for example +1M or -500K.",
    admin_empty_input = "Enter a value before choosing Set.",
    admin_next_player_label = "Next player",
    admin_result_ready = "Choose a target and an action. Local previews and client logging affect only you.",
    colors = {
        input = { 35, 35, 44 },
        text = { 255, 255, 255 },
        muted_text = { 200, 200, 210 },
        action = { 0, 120, 180 },
    },
}
