-- Canonical paired performances. Both realms teach the same authoritative Merge tutorial.
return {
    version = 1,
    status = "recorded",
    language = "en",
    playbackVolumeSource = {
        config = "merge_egg_prototype",
        angel = {
            "watcher",
            "voice",
            "volume",
        },
        demon = {
            "watcher",
            "themes",
            "hell",
            "voice",
            "volume",
        },
    },
    sections = {
        {
            id = "heaven",
            title = "Heaven — Angel",
            speaker = "angel",
            lines = {
                {
                    id = "MA01",
                    cue = "merge_tutorial.heaven.collect_setup",
                    usage = "main",
                    condition = "Opening collection",
                    text = "Welcome to your little corner of Heaven. Follow the glowing trail to gather the Waycoins, then the gem. We’ll turn them into a brave little defense.",
                },
                {
                    id = "MA02",
                    cue = "merge_tutorial.heaven.collect_setup.auto",
                    usage = "main",
                    condition = "Opening collection with Auto Collector",
                    text = "Your Coin Pup is already gathering our supplies. Let that helpful little nose collect the coins and gem; then we’ll put them to good use.",
                },
                {
                    id = "MA03",
                    cue = "merge_tutorial.heaven.create_five",
                    usage = "main",
                    condition = "Five opening eggs",
                    text = "Now, let’s build your first defense. Use Buy Egg to create five Earth Eggs. There’s a whole little squad waiting to begin.",
                },
                {
                    id = "MA04",
                    cue = "merge_tutorial.heaven.deploy_best",
                    usage = "main",
                    condition = "Both legacy deployment steps",
                    text = "Lovely. Choose Deploy Best, and your eggs will take their places on the defense line. Your little guardians can handle the first arrivals.",
                },
                {
                    id = "MA05",
                    cue = "merge_tutorial.heaven.collect_workshop_coins",
                    usage = "main",
                    condition = "Bulwark installation needs coins",
                    text = "Before we strengthen the line, gather a Waycoin pile. The engineer needs a little funding to bring his work to life.",
                },
                {
                    id = "MA06",
                    cue = "merge_tutorial.heaven.talk_engineer",
                    usage = "main",
                    condition = "Gold-line engineer",
                    text = "Our engineer has arrived at the gold line. Follow the guide and speak with him. A sturdy defense can give every guardian a little more time.",
                },
                {
                    id = "MA07",
                    cue = "merge_tutorial.heaven.unlock_bulwark",
                    usage = "main",
                    condition = "Unlock Impaler Palisade",
                    text = "Unlock the Impaler Palisade with your gem. Those sharp little points will help your new wall stand up to trouble.",
                },
                {
                    id = "MA08",
                    cue = "merge_tutorial.heaven.install_bulwark",
                    usage = "main",
                    condition = "Install unlocked bulwark",
                    text = "Now choose Install. There—another layer of protection for your brave little defenders. We’re building something worth holding onto.",
                },
                {
                    id = "MA09",
                    cue = "merge_tutorial.heaven.collect_cannon_coins",
                    usage = "main",
                    condition = "Cannon installation needs coins",
                    text = "Gather a Waycoin pile for the next improvement. A little support from the artillery commander will help your line last longer.",
                },
                {
                    id = "MA10",
                    cue = "merge_tutorial.heaven.collect_cannon_gem",
                    usage = "main",
                    condition = "Collect cannon unlock gem",
                    text = "Follow the guide to the gem. Keep it close; it will unlock a cannon that helps mend your defense.",
                },
                {
                    id = "MA11",
                    cue = "merge_tutorial.heaven.talk_commander",
                    usage = "main",
                    condition = "Right-pad artillery commander",
                    text = "The artillery commander is ready at the right-hand gun. Follow the guide and speak with him. Even the strongest line deserves a little care.",
                },
                {
                    id = "MA12",
                    cue = "merge_tutorial.heaven.unlock_cannon",
                    usage = "main",
                    condition = "Unlock Heal cannon",
                    text = "Choose Unlock for the Heal cannon. Your gem will open a gentler kind of artillery—one that helps keep your defense standing.",
                },
                {
                    id = "MA13",
                    cue = "merge_tutorial.heaven.install_cannon",
                    usage = "main",
                    condition = "Install Heal cannon",
                    text = "Choose Install, and let the Heal cannon join your defense. A little kindness in the right place can make a wonderful difference.",
                },
                {
                    id = "MA14",
                    cue = "merge_tutorial.heaven.power_lesson",
                    usage = "main",
                    condition = "Wave 6 power choice",
                    text = "You’ve earned a new power. Open Powers and choose one, then Commit. Magnet is a helpful first choice for bringing scattered loot a little closer.",
                },
                {
                    id = "MA15",
                    cue = "merge_tutorial.heaven.collect_upgrade_coins",
                    usage = "main",
                    condition = "Wave 8 optional egg improvement funding",
                    text = "Let’s gather a few more Waycoins for your eggs. Follow the guide; a stronger line begins with one small improvement at a time.",
                },
                {
                    id = "MA16",
                    cue = "merge_tutorial.heaven.collect_upgrade_coins.auto",
                    usage = "main",
                    condition = "Upgrade funding with Auto Collector",
                    text = "Your Coin Pup will gather what we need. Give that faithful little helper a moment, and we’ll improve your defense together.",
                },
                {
                    id = "MA17",
                    cue = "merge_tutorial.heaven.upgrade_eggs",
                    usage = "main",
                    condition = "Optional improvement, purchase phase",
                    text = "Let’s give your line a little more strength. Buy a couple of eggs, then use Deploy Best. If you already have an egg, placing it works too.",
                },
                {
                    id = "MA18",
                    cue = "merge_tutorial.heaven.upgrade_eggs.deploy",
                    usage = "main",
                    condition = "Optional improvement, deploy phase",
                    text = "Your eggs are ready. Choose Deploy Best to combine matching eggs or place one on the line. Either is a good next step.",
                },
                {
                    id = "MA19",
                    cue = "merge_tutorial.heaven.slots_lesson",
                    usage = "main",
                    condition = "Wave 10 slot choice",
                    text = "Let’s make room for your powers to grow. In Powers, choose two extra enhancement slots, then Commit. You can change your picks before committing.",
                },
                {
                    id = "MA20",
                    cue = "merge_tutorial.heaven.enhance_lesson",
                    usage = "main",
                    condition = "Wave 12 enhancement lesson",
                    text = "Now we can give a power a little more sparkle. Choose it in Powers, and let’s fit an enhancement into one of its slots.",
                },
                {
                    id = "MA21",
                    cue = "merge_tutorial.heaven.talk_quartermaster",
                    usage = "main",
                    condition = "Wave 14 timed introduction; visit optional",
                    text = "Meet Macros, your Quartermaster. He has boosts, enhancements, and optional training whenever you want them. There’s no need to visit right now; your adventure is yours.",
                },
                {
                    id = "MA22",
                    cue = "merge_tutorial.heaven.after_setup",
                    usage = "main",
                    condition = "Opening deployment releases combat",
                    text = "Your guardians are ready. Try spreading your defense across more hatchers; two smaller squads can serve you better than one powerful egg. It’s your choice.",
                },
                {
                    id = "MA23",
                    cue = "merge_tutorial.heaven.after_bulwark",
                    usage = "main",
                    condition = "Bulwark lesson releases combat",
                    text = "Your wall is in place. Let’s see how the line holds now. Each small improvement gives your guardians a little more breathing room.",
                },
                {
                    id = "MA24",
                    cue = "merge_tutorial.heaven.after_cannon",
                    usage = "main",
                    condition = "Cannon lesson releases combat",
                    text = "Your Heal cannon is ready. Keep the defense going; there’s a new power waiting a little further along.",
                },
                {
                    id = "MA25",
                    cue = "merge_tutorial.heaven.after_power",
                    usage = "main",
                    condition = "Power lesson releases combat",
                    text = "That power is yours now. Try it when it will help, and keep your defense growing. You’re finding your own way.",
                },
                {
                    id = "MA26",
                    cue = "merge_tutorial.heaven.after_upgrade",
                    usage = "main",
                    condition = "Egg improvement releases combat",
                    text = "That’s a little stronger already. Let your guardians get back to work. You can keep improving the line as you go.",
                },
                {
                    id = "MA27",
                    cue = "merge_tutorial.heaven.after_slots",
                    usage = "main",
                    condition = "Slot lesson releases combat",
                    text = "Your extra slots are ready. Keep the line steady, and soon we’ll give one of your powers a useful enhancement.",
                },
                {
                    id = "MA28",
                    cue = "merge_tutorial.heaven.after_enhance",
                    usage = "main",
                    condition = "Enhancement lesson releases combat",
                    text = "There—that power has a little more to offer. Keep going; you’ve nearly learned everything you need to manage this defense yourself.",
                },
                {
                    id = "MA29",
                    cue = "merge_tutorial.heaven.completion",
                    usage = "main",
                    condition = "Live final completion only",
                    text = "You’ve learned the essentials, little light. Keep growing your defense, explore when you wish, and remember: you can always take a breather in Farm and Fight.",
                },
                {
                    id = "MA30",
                    cue = "merge_tutorial.heaven.resume",
                    usage = "main",
                    condition = "Rejoining an unfinished hands-on lesson",
                    text = "Welcome back, little light. Your progress is still here. Follow the guide, and we’ll pick up with the step you were working on.",
                },
                {
                    id = "MA31",
                    cue = "merge_tutorial.heaven.reminder",
                    usage = "reminder",
                    condition = "Recurring idle encouragement during required hands-on lessons",
                    text = "Whenever you’re ready, little light, the glowing guide will show your next step. Take your time. We’ll build this together.",
                },
                {
                    id = "MA32",
                    cue = "merge_tutorial.heaven.help.power",
                    usage = "help",
                    condition = "Power menu choice",
                    text = "Magnet is a helpful beginning. Choose the power you want, then Commit when you’re happy with your choice.",
                },
                {
                    id = "MA33",
                    cue = "merge_tutorial.heaven.help.slots",
                    usage = "help",
                    condition = "Power menu slot allocation",
                    text = "Choose two extra slots on powers you own. You can put them where they’ll help most, and change your picks before you Commit.",
                },
                {
                    id = "MA34",
                    cue = "merge_tutorial.heaven.help.commit",
                    usage = "help",
                    condition = "Commit staged choices",
                    text = "Your choices are ready. Choose Commit to make them yours, or adjust them first if something doesn’t feel right.",
                },
                {
                    id = "MA35",
                    cue = "merge_tutorial.heaven.help.owned",
                    usage = "help",
                    condition = "Choose an owned power to enhance",
                    text = "Choose one of your powers. Then we can look at its slots and find a home for that enhancement.",
                },
                {
                    id = "MA36",
                    cue = "merge_tutorial.heaven.help.slot",
                    usage = "help",
                    condition = "Choose an enhancement slot",
                    text = "Choose an empty enhancement slot on that power. A small space, with room for something helpful.",
                },
                {
                    id = "MA37",
                    cue = "merge_tutorial.heaven.help.enhancement",
                    usage = "help",
                    condition = "Choose a compatible enhancement",
                    text = "Choose an enhancement that fits your power. A Focus enhancement can help it use less of your energy.",
                },
                {
                    id = "MA38",
                    cue = "merge_tutorial.heaven.help.apply",
                    usage = "help",
                    condition = "Apply the selected enhancement",
                    text = "That looks ready. Choose Apply to place the enhancement into your power. Then let’s see what it can do.",
                },
                {
                    id = "MA39",
                    cue = "merge_tutorial.heaven.help.origin",
                    usage = "help",
                    condition = "Origin choice encountered during low-level power guidance",
                    text = "This choice shapes the powers you can learn. Take a moment to explore the origins, and choose the one that feels right for you.",
                },
                {
                    id = "MA40",
                    cue = "merge_tutorial.heaven.help.origin_review",
                    usage = "help",
                    condition = "Permanent origin confirmation",
                    text = "Take one last look before you confirm. Your origin is a permanent choice, so choose the path you truly want to follow.",
                },
            },
        },
        {
            id = "hell",
            title = "Hell — Demon",
            speaker = "demon",
            lines = {
                {
                    id = "MD01",
                    cue = "merge_tutorial.hell.collect_setup",
                    usage = "main",
                    condition = "Opening collection",
                    text = "So, this patch of Hell is yours. Collect the Waycoins along the glowing trail, then the gem. Even impending disaster needs a starting budget.",
                },
                {
                    id = "MD02",
                    cue = "merge_tutorial.hell.collect_setup.auto",
                    usage = "main",
                    condition = "Opening collection with Auto Collector",
                    text = "You brought a Coin Pup. Delegating already? Sensible. Let it collect the coins and gem while you practice looking like you’re in charge.",
                },
                {
                    id = "MD03",
                    cue = "merge_tutorial.hell.create_five",
                    usage = "main",
                    condition = "Five opening eggs",
                    text = "Five Earth Eggs. Use Buy Egg until you have them. Yes, eggs. Apparently that is what stands between you and utter embarrassment.",
                },
                {
                    id = "MD04",
                    cue = "merge_tutorial.hell.deploy_best",
                    usage = "main",
                    condition = "Both legacy deployment steps",
                    text = "Choose Deploy Best. It puts those eggs to work on your defense line. They cannot defend much while you leave them admiring the board.",
                },
                {
                    id = "MD05",
                    cue = "merge_tutorial.hell.collect_workshop_coins",
                    usage = "main",
                    condition = "Bulwark installation needs coins",
                    text = "Fetch a Waycoin pile. The engineer does not accept hopeful expressions as payment. I asked.",
                },
                {
                    id = "MD06",
                    cue = "merge_tutorial.hell.talk_engineer",
                    usage = "main",
                    condition = "Gold-line engineer",
                    text = "The engineer is waiting at the gold line. Go speak with him. A wall might compensate for that optimistic approach to survival.",
                },
                {
                    id = "MD07",
                    cue = "merge_tutorial.hell.unlock_bulwark",
                    usage = "main",
                    condition = "Unlock Impaler Palisade",
                    text = "Unlock the Impaler Palisade. One gem buys a rather pointed objection to trespassers. Finally, a decorating choice I approve of.",
                },
                {
                    id = "MD08",
                    cue = "merge_tutorial.hell.install_bulwark",
                    usage = "main",
                    condition = "Install unlocked bulwark",
                    text = "Choose Install. Owning a wall and actually putting it in the enemy’s way are, regrettably, different things.",
                },
                {
                    id = "MD09",
                    cue = "merge_tutorial.hell.collect_cannon_coins",
                    usage = "main",
                    condition = "Cannon installation needs coins",
                    text = "Another Waycoin pile, please. Artillery is wonderfully persuasive, but apparently persuasion has installation costs.",
                },
                {
                    id = "MD10",
                    cue = "merge_tutorial.hell.collect_cannon_gem",
                    usage = "main",
                    condition = "Collect cannon unlock gem",
                    text = "Collect that gem. We’re unlocking a Heal cannon. Try not to look so disappointed that it does something useful.",
                },
                {
                    id = "MD11",
                    cue = "merge_tutorial.hell.talk_commander",
                    usage = "main",
                    condition = "Right-pad artillery commander",
                    text = "Your artillery commander is waiting by the right-hand gun. Go introduce yourself before your defense introduces itself to the floor.",
                },
                {
                    id = "MD12",
                    cue = "merge_tutorial.hell.unlock_cannon",
                    usage = "main",
                    condition = "Unlock Heal cannon",
                    text = "Unlock Heal with your gem. Yes, healing artillery. Apparently keeping your defenders alive is part of the strategy.",
                },
                {
                    id = "MD13",
                    cue = "merge_tutorial.hell.install_cannon",
                    usage = "main",
                    condition = "Install Heal cannon",
                    text = "Choose Install. Let the Heal cannon earn its place. Your defenders have been very patient with your management so far.",
                },
                {
                    id = "MD14",
                    cue = "merge_tutorial.hell.power_lesson",
                    usage = "main",
                    condition = "Wave 6 power choice",
                    text = "You’ve earned a power. Open Powers, choose one, and Commit. Magnet can collect scattered loot. Anything that reduces your wandering is progress.",
                },
                {
                    id = "MD15",
                    cue = "merge_tutorial.hell.collect_upgrade_coins",
                    usage = "main",
                    condition = "Wave 8 optional egg improvement funding",
                    text = "Gather some more Waycoins. Your eggs could use an improvement, and glaring at them has achieved remarkably little.",
                },
                {
                    id = "MD16",
                    cue = "merge_tutorial.hell.collect_upgrade_coins.auto",
                    usage = "main",
                    condition = "Upgrade funding with Auto Collector",
                    text = "Let your Coin Pup gather the funds. At least one member of this operation understands the assignment.",
                },
                {
                    id = "MD17",
                    cue = "merge_tutorial.hell.upgrade_eggs",
                    usage = "main",
                    condition = "Optional improvement, purchase phase",
                    text = "Time to improve those eggs. Buy a couple, then use Deploy Best. Already have one waiting? Place it. I’m mocking you, not trying to trap you.",
                },
                {
                    id = "MD18",
                    cue = "merge_tutorial.hell.upgrade_eggs.deploy",
                    usage = "main",
                    condition = "Optional improvement, deploy phase",
                    text = "Choose Deploy Best. It can combine matching eggs or place one on the line. Either counts. Do try to contain your relief.",
                },
                {
                    id = "MD19",
                    cue = "merge_tutorial.hell.slots_lesson",
                    usage = "main",
                    condition = "Wave 10 slot choice",
                    text = "Two extra enhancement slots are yours to choose. Open Powers, place them, and Commit. You may reconsider before committing. A rare luxury.",
                },
                {
                    id = "MD20",
                    cue = "merge_tutorial.hell.enhance_lesson",
                    usage = "main",
                    condition = "Wave 12 enhancement lesson",
                    text = "Those new slots are not merely decorative. Choose a power in Powers, and fit it with an enhancement. Let’s see some improvement.",
                },
                {
                    id = "MD21",
                    cue = "merge_tutorial.hell.talk_quartermaster",
                    usage = "main",
                    condition = "Wave 14 timed introduction; visit optional",
                    text = "That’s Macros, your Quartermaster. Boosts, enhancements, optional training. Visit when you like. For once, I am not giving you homework.",
                },
                {
                    id = "MD22",
                    cue = "merge_tutorial.hell.after_setup",
                    usage = "main",
                    condition = "Opening deployment releases combat",
                    text = "Eggs in one basket? How traditional. Try filling another hatcher; two smaller squads can serve you better than one powerful egg. Your defense, your decision.",
                },
                {
                    id = "MD23",
                    cue = "merge_tutorial.hell.after_bulwark",
                    usage = "main",
                    condition = "Bulwark lesson releases combat",
                    text = "A wall, installed correctly. I shall try not to sound surprised. Let the next enemies test your handiwork.",
                },
                {
                    id = "MD24",
                    cue = "merge_tutorial.hell.after_cannon",
                    usage = "main",
                    condition = "Cannon lesson releases combat",
                    text = "The Heal cannon is installed. Let’s see whether your defense survives long enough to earn its next lesson.",
                },
                {
                    id = "MD25",
                    cue = "merge_tutorial.hell.after_power",
                    usage = "main",
                    condition = "Power lesson releases combat",
                    text = "A power of your own. Use it when it helps. I’d hate for it to become another expensive ornament.",
                },
                {
                    id = "MD26",
                    cue = "merge_tutorial.hell.after_upgrade",
                    usage = "main",
                    condition = "Egg improvement releases combat",
                    text = "An improvement. I noticed. Your guardians may return to work while I recover from this unexpected competence.",
                },
                {
                    id = "MD27",
                    cue = "merge_tutorial.hell.after_slots",
                    usage = "main",
                    condition = "Slot lesson releases combat",
                    text = "Your slots are ready. Hold the line a little longer, and we’ll put something useful in one of them.",
                },
                {
                    id = "MD28",
                    cue = "merge_tutorial.hell.after_enhance",
                    usage = "main",
                    condition = "Enhancement lesson releases combat",
                    text = "An enhanced power. Better. Keep the defense going. You are becoming inconveniently capable.",
                },
                {
                    id = "MD29",
                    cue = "merge_tutorial.hell.completion",
                    usage = "main",
                    condition = "Live final completion only",
                    text = "That concludes your introduction to barely controlled chaos. Keep improving your defense. Explore if you like. You may even visit Farm and Fight. I shall endure your absence.",
                },
                {
                    id = "MD30",
                    cue = "merge_tutorial.hell.resume",
                    usage = "main",
                    condition = "Rejoining an unfinished hands-on lesson",
                    text = "Back for more? Your progress survived. Follow the guide, and we’ll resume the part you were so thoughtfully contemplating.",
                },
                {
                    id = "MD31",
                    cue = "merge_tutorial.hell.reminder",
                    usage = "reminder",
                    condition = "Recurring idle encouragement during required hands-on lessons",
                    text = "Your next step is still waiting by the glowing guide. No rush. The enemies have only their entire existence to spare.",
                },
                {
                    id = "MD32",
                    cue = "merge_tutorial.hell.help.power",
                    usage = "help",
                    condition = "Power menu choice",
                    text = "Choose a power, then Commit. Magnet is useful. So, I’m told, is making a decision.",
                },
                {
                    id = "MD33",
                    cue = "merge_tutorial.hell.help.slots",
                    usage = "help",
                    condition = "Power menu slot allocation",
                    text = "Place your extra slots on powers you own. Change your picks if you must, then Commit. Empty deliberation is not an enhancement.",
                },
                {
                    id = "MD34",
                    cue = "merge_tutorial.hell.help.commit",
                    usage = "help",
                    condition = "Commit staged choices",
                    text = "Your choices are waiting. Commit to keep them, or adjust them first. Staring at the button is not a third option.",
                },
                {
                    id = "MD35",
                    cue = "merge_tutorial.hell.help.owned",
                    usage = "help",
                    condition = "Choose an owned power to enhance",
                    text = "Choose a power you own. We need somewhere to put the enhancement, preferably somewhere useful.",
                },
                {
                    id = "MD36",
                    cue = "merge_tutorial.hell.help.slot",
                    usage = "help",
                    condition = "Choose an enhancement slot",
                    text = "Choose an empty slot on that power. Yes, the empty one. We’re filling it, not admiring it.",
                },
                {
                    id = "MD37",
                    cue = "merge_tutorial.hell.help.enhancement",
                    usage = "help",
                    condition = "Choose a compatible enhancement",
                    text = "Choose a fitting enhancement. Focus reduces the energy your power spends. Efficiency. Such a refreshing concept.",
                },
                {
                    id = "MD38",
                    cue = "merge_tutorial.hell.help.apply",
                    usage = "help",
                    condition = "Apply the selected enhancement",
                    text = "Choose Apply. The enhancement does rather more inside the power than it does sitting in a menu.",
                },
                {
                    id = "MD39",
                    cue = "merge_tutorial.hell.help.origin",
                    usage = "help",
                    condition = "Origin choice encountered during low-level power guidance",
                    text = "Choosing an origin? That shapes the powers you can learn. Read the choices. Even I would not rush you through this one.",
                },
                {
                    id = "MD40",
                    cue = "merge_tutorial.hell.help.origin_review",
                    usage = "help",
                    condition = "Permanent origin confirmation",
                    text = "One last look before you confirm. Your origin is permanent. For this decision, thinking twice is entirely acceptable.",
                },
            },
        },
    },
}
