-- Disconnected-account workers. The online test button stays Studio-only.
return {
    enabled = true,
    studio_enabled = true,
    excluded_user_ids = { 3200870803 }, -- Colorado Plays; other exact internal IDs may participate.
    pass = "offline_gaming",
    maximum_bays = 5,
    heartbeat_seconds = 15,
    lease_seconds = 90,
    fill_seconds = 20,
    selection_count = 40,
    acquisition_attempts = 3,
    studio_fixture_user_id = -100001,
    studio_stress = {
        maximum_occupied_bays = 8,
        first_fixture_user_id = -200001,
        duration_seconds = 1800,
        profile_seconds = 20,
    },
    pool_sort_range = 1000000000,
    rotation_seconds = 1800,
    load_timeout_seconds = 20,
    logout_grace_seconds = 60,
    presence_map = "MergeOfflinePresence_v1",
    pool_store = "MergeOfflinePool_v1",
    login_topic = "MergeOfflineLogin_v1",
    namespace = "MergeOfflineWorkers",
    name_prefix = "Offline ",
    display_suffix = " • OFFLINE",
    claim_action_text = "Claim Bay",
    walk_speed = 24,
    navigation_seconds = 1,
    max_navigation_waypoints = 80,
    profile_summary_key = "OfflineMerge",
    summary_title = "OFFLINE EARNINGS",
    summary_body = "Your offline earnings are already in your account.",
    summary_details = "%s\n%d XP · %d gems · %d minutes played",
}
