-- Version names whenever step meanings change: Roblox fills skipped steps automatically.
return {
    enabled = true,
    queue_limit = 1024,
    send_interval = 0.5,
    retry_limit = 3,
    entry_timeout_seconds = 45,
    trace_limit = 120,
    leave_flush_limit = 12,
    -- Native filters combine mode + realm; the existing raw archive retains separate dimensions.
    archive_event = "merge_analytics",
    context_version = 1,
    funnels = {
        entry = {
            name = "Merge Entry v1",
            steps = {
                { "joined", "Joined Merge server" },
                { "profile_ready", "Profile ready" },
                { "bay_claimed", "Bay assigned" },
                { "session_ready", "Session armed and restored" },
                { "wave_started", "First live wave started" },
            },
        },
        activation = {
            name = "Merge Activation v1",
            fresh_only = true,
            steps = {
                { "session_ready", "Fresh board ready" },
                { "egg_created", "Bought first egg" },
                { "egg_placed", "Placed egg on defense line" },
                { "wave_started", "Started wave" },
                { "wave_cleared", "Resolved first wave alive" },
            },
        },
        depth = {
            name = "Merge Run Depth v1",
            steps = {
                { "session_ready", "Bay session ready" },
                { "clears_1", "1 new wave resolved" },
                { "clears_5", "5 new waves resolved" },
                { "clears_10", "10 new waves resolved" },
                { "clears_25", "25 new waves resolved" },
                { "clears_50", "50 new waves resolved" },
                { "clears_100", "100 new waves resolved" },
            },
        },
        artillery = {
            name = "Merge Artillery v1",
            steps = {
                { "cannon_opened", "Artillery interaction accepted" },
                { "cannon_purchased", "Installed or upgraded artillery" },
                { "cannon_upgraded", "Upgraded artillery" },
            },
        },
        bulwark = {
            name = "Merge Bulwark v1",
            steps = {
                { "bulwark_opened", "Bulwark interaction accepted" },
                { "bulwark_purchased", "Installed or upgraded bulwark" },
                { "bulwark_upgraded", "Upgraded bulwark" },
            },
        },
        rebirth = {
            name = "Merge Rebirth v1",
            steps = {
                { "rebirth_eligible", "Rebirth requirements and funds ready" },
                { "rebirth_confirmed", "Confirmed rebirth request" },
                { "rebirth_completed", "Rebirth completed" },
            },
        },
        autoplay = {
            enabled = false, -- Keep custom milestones; reserve native funnel capacity for courses.
            name = "Merge Autoplay v1",
            steps = {
                { "autoplay_owned", "Autoplay entitlement available" },
                { "autoplay_enabled", "Autoplay enabled" },
                { "autoplay_action", "First successful automated action" },
                { "auto_actions_10", "10 successful automated actions" },
            },
        },
    },
    wave_thresholds = { 1, 5, 10, 25, 50, 100 },
    autoplay_thresholds = { 10 },
    custom = {
        tutorial = "Merge Tutorial v1",
        milestone = "Merge Milestone v1",
        failure = "Merge Failure v1",
        exit = "Merge Exit v1",
    },
    tutorial_stages = {
        combat_waves = true,
        cannon_waves = true,
        upgrade_waves = true,
        quartermaster_waves = true,
        complete = true,
    },
    milestones = {
        coin_collected = true,
        egg_created = true,
        egg_placed = true,
        board_merged = true,
        base_upgraded = true,
        cannon_unlocked = true,
        bulwark_unlocked = true,
        cannon_purchased = true,
        bulwark_purchased = true,
        rebirth_completed = true,
        autoplay_enabled = true,
        autoplay_action = true,
        defense_overrun = true,
    },
    failure_reasons = {
        bay_occupied = true,
        no_available_bay = true,
        no_available_bays = true,
        session_ended = true,
        world_or_character_unavailable = true,
        profile_timeout = true,
        entry_timeout = true,
        character_unavailable = true,
        wave_config_missing = true,
        enemy_march_anchor_missing = true,
        defense_team_missing = true,
        not_enough_currency = true,
        insufficient_funds = true,
        insufficient_currency = true,
        rebirth_egg_requirement = true,
        station_too_far = true,
        replacement_confirmation_required = true,
        not_active_encounter = true,
    },
    failure_actions = {
        entry = true,
        create = true,
        upgrade_base = true,
        merge = true,
        place = true,
        cannon = true,
        bulwark = true,
        rebirth = true,
        board = true,
        autoplay = true,
    },
    exit_reasons = { leave = true, ended = true, reset = true, replaced = true, shutdown = true },
}
