-- Merge owns cue selection; tutorial_voice owns the shared presentation and mix timing.
return {
    enabled = true,
    group_name = "MergeTutorialVoice",
    side_speakers = { heaven = "angel", hell = "demon" },
    steps = {
        collect_setup = "collect_setup",
        create_five = "create_five",
        combine_once = "deploy_best",
        deploy_one = "deploy_best",
        collect_workshop_coins = "collect_workshop_coins",
        talk_engineer = "talk_engineer",
        unlock_bulwark = "unlock_bulwark",
        install_bulwark = "install_bulwark",
        collect_cannon_coins = "collect_cannon_coins",
        collect_cannon_gem = "collect_cannon_gem",
        talk_commander = "talk_commander",
        unlock_cannon = "unlock_cannon",
        install_cannon = "install_cannon",
        power_lesson = "power_lesson",
        collect_upgrade_coins = "collect_upgrade_coins",
        upgrade_eggs = "upgrade_eggs",
        slots_lesson = "slots_lesson",
        enhance_lesson = "enhance_lesson",
        talk_quartermaster = "talk_quartermaster",
    },
    auto_steps = {
        collect_setup = "collect_setup.auto",
        collect_upgrade_coins = "collect_upgrade_coins.auto",
    },
    after_steps = {
        create_five = "after_setup",
        combine_once = "after_setup",
        deploy_one = "after_setup",
        collect_workshop_coins = "after_bulwark",
        talk_engineer = "after_bulwark",
        unlock_bulwark = "after_bulwark",
        install_bulwark = "after_bulwark",
        collect_cannon_coins = "after_cannon",
        collect_cannon_gem = "after_cannon",
        talk_commander = "after_cannon",
        unlock_cannon = "after_cannon",
        install_cannon = "after_cannon",
        power_lesson = "after_power",
        collect_upgrade_coins = "after_upgrade",
        upgrade_eggs = "after_upgrade",
        slots_lesson = "after_slots",
        enhance_lesson = "after_enhance",
    },
    power_help = {
        power = "help.power",
        slots = "help.slots",
        commit = "help.commit",
        owned = "help.owned",
        slot = "help.slot",
        enhancement = "help.enhancement",
        apply = "help.apply",
        origin = "help.origin",
        origin_review = "help.origin_review",
    },
    power_steps = { power_lesson = true, slots_lesson = true, enhance_lesson = true },
    resume_cue = "resume",
    completion_cue = "completion",
    reminder_cue = "reminder",
}
