-- Version names whenever step meanings change: Roblox fills skipped steps automatically.
return {
    enabled = true,
    queue_limit = 1024,
    send_interval = 0.5,
    retry_limit = 3,
    entry_timeout_seconds = 45,
    trace_limit = 120,
    leave_flush_limit = 12,
    -- Native filters combine mode + realm; the existing raw archive retains separate dimensions.
    archive_event = "merge_analytics",
    context_version = 1,
    funnels = {
        entry = {
            name = "Merge Entry v1",
            steps = {
                { "joined", "Joined Merge server" },
                { "profile_ready", "Profile ready" },
                { "bay_claimed", "Bay assigned" },
                { "session_ready", "Session armed and restored" },
                { "wave_started", "First live wave started" },
            },
        },
        activation = {
            name = "Merge Onboarding v2",
            fresh_only = true,
            onboarding_only = true,
            steps = {
                { "session_ready", "Fresh onboarding bay ready" },
                { "coin_collected", "Collected opening coins" },
                { "egg_created", "Bought first egg" },
                { "egg_placed", "Placed egg on defense line" },
                { "wave_started", "Started first live wave" },
                { "wave_resolved_1", "Resolved Wave 1 alive" },
                { "wave_resolved_2", "Resolved Wave 2 alive" },
                { "bulwark_opened", "Opened bulwark workshop" },
                { "bulwark_purchased", "Installed or upgraded bulwark" },
                { "wave_resolved_3", "Resolved Wave 3 alive" },
                { "wave_resolved_4", "Resolved Wave 4 alive" },
                { "cannon_opened", "Opened artillery workshop" },
                { "cannon_purchased", "Installed or upgraded artillery" },
                { "wave_resolved_5", "Resolved Wave 5 alive" },
                { "wave_resolved_6", "Resolved Wave 6 alive" },
                { "power_lesson_completed", "Level 2 claimed and power choice ready" },
                { "wave_resolved_7", "Resolved Wave 7 alive" },
                { "wave_resolved_8", "Resolved Wave 8 alive" },
                { "wave_resolved_9", "Resolved Wave 9 alive" },
                { "wave_resolved_10", "Resolved Wave 10 alive" },
                { "slots_lesson_completed", "Level 3 claimed and two earned slots allocated" },
                { "wave_resolved_11", "Resolved Wave 11 alive" },
                { "wave_resolved_12", "Resolved Wave 12 alive" },
                { "enhance_lesson_completed", "Usable power enhancement equipped" },
                { "wave_resolved_13", "Resolved Wave 13 alive" },
                { "wave_resolved_14", "Resolved Wave 14 alive" },
                { "onboarding_completed", "Quartermaster introduction and onboarding complete" },
                { "wave_resolved_15", "Resolved Wave 15 alive" },
                { "wave_resolved_16", "Resolved Wave 16 alive" },
                { "wave_resolved_17", "Resolved Wave 17 alive" },
                { "wave_resolved_18", "Resolved Wave 18 alive" },
                { "wave_resolved_19", "Resolved Wave 19 alive" },
                { "wave_resolved_20", "Resolved Wave 20 alive" },
            },
        },
        depth = {
            name = "Merge Run Depth v1",
            steps = {
                { "session_ready", "Bay session ready" },
                { "clears_1", "1 new wave resolved" },
                { "clears_5", "5 new waves resolved" },
                { "clears_10", "10 new waves resolved" },
                { "clears_25", "25 new waves resolved" },
                { "clears_50", "50 new waves resolved" },
                { "clears_100", "100 new waves resolved" },
            },
        },
        artillery = {
            name = "Merge Artillery v1",
            steps = {
                { "cannon_opened", "Artillery interaction accepted" },
                { "cannon_purchased", "Installed or upgraded artillery" },
                { "cannon_upgraded", "Upgraded artillery" },
            },
        },
        bulwark = {
            name = "Merge Bulwark v1",
            steps = {
                { "bulwark_opened", "Bulwark interaction accepted" },
                { "bulwark_purchased", "Installed or upgraded bulwark" },
                { "bulwark_upgraded", "Upgraded bulwark" },
            },
        },
        rebirth = {
            name = "Merge Rebirth v1",
            steps = {
                { "rebirth_eligible", "Rebirth requirements and funds ready" },
                { "rebirth_confirmed", "Confirmed rebirth request" },
                { "rebirth_completed", "Rebirth completed" },
            },
        },
        autoplay = {
            enabled = false, -- Keep custom milestones; reserve native funnel capacity for courses.
            name = "Merge Autoplay v1",
            steps = {
                { "autoplay_owned", "Autoplay entitlement available" },
                { "autoplay_enabled", "Autoplay enabled" },
                { "autoplay_action", "First successful automated action" },
                { "auto_actions_10", "10 successful automated actions" },
            },
        },
    },
    wave_thresholds = { 1, 5, 10, 25, 50, 100 },
    early_wave_limit = 20,
    autoplay_thresholds = { 10 },
    custom = {
        tutorial = "Merge Tutorial v1",
        milestone = "Merge Milestone v1",
        failure = "Merge Failure v1",
        exit = "Merge Exit v2",
        wave = "Merge Early Wave v2",
    },
    tutorial_stages = {
        power_lesson = true,
        slots_lesson = true,
        enhance_lesson = true,
        combat_waves = true,
        cannon_waves = true,
        upgrade_waves = true,
        quartermaster_waves = true,
        complete = true,
    },
    milestones = {
        full_mode_active = true,
        full_starter_pets_granted = true,
        power_lesson_completed = true,
        slots_lesson_completed = true,
        enhance_lesson_completed = true,
        egg_lesson_completed = true,
        onboarding_completed = true,
        coin_collected = true,
        egg_created = true,
        egg_placed = true,
        board_merged = true,
        base_upgraded = true,
        cannon_unlocked = true,
        bulwark_unlocked = true,
        cannon_purchased = true,
        bulwark_purchased = true,
        rebirth_completed = true,
        autoplay_enabled = true,
        autoplay_action = true,
        defense_overrun = true,
    },
    failure_reasons = {
        bay_occupied = true,
        no_available_bay = true,
        no_available_bays = true,
        session_ended = true,
        world_or_character_unavailable = true,
        profile_timeout = true,
        entry_timeout = true,
        character_unavailable = true,
        wave_config_missing = true,
        enemy_march_anchor_missing = true,
        defense_team_missing = true,
        not_enough_currency = true,
        insufficient_funds = true,
        insufficient_currency = true,
        rebirth_egg_requirement = true,
        station_too_far = true,
        replacement_confirmation_required = true,
        not_active_encounter = true,
    },
    failure_actions = {
        entry = true,
        create = true,
        upgrade_base = true,
        merge = true,
        place = true,
        cannon = true,
        bulwark = true,
        rebirth = true,
        board = true,
        autoplay = true,
    },
    exit_reasons = { leave = true, ended = true, reset = true, replaced = true, shutdown = true },
}
