-- Online character automation, sold by the existing Offline Gaming pass. No offline accrual,
-- anti-idle input synthesis, Gem spending, level claiming, or player rebirth is implied.
return {
    enabled = true,
    pass_id = "offline_gaming",
    entitlement_feature = "merge_autoplay",
    currency = "hall_coins",
    tick_seconds = 0.5,
    action_seconds = 0.75,
    target_timeout_seconds = 22,
    blocked_retry_seconds = 15,
    maximum_failures = 8,
    report_seconds = 60,
    history_limit = 40,
    arrival_distance = 7,
    collect_distance = 4,
    maximum_vertical_distance = 8,
    request_seconds = 0.5,
    default_strategy = "balanced",
    strategies = {
        balanced = {
            sequence = { "eggs", "cannon", "eggs", "bulwark" },
            cannons = { "heal", "rage", "debuff", "gravity", "repulsor", "nullifier" },
            bulwarks = {
                "impaler_palisade",
                "saw_blade",
                "land_shark",
                "concertina_line",
                "grasping_hedge",
                "wardstone_barrier",
            },
        },
        egg_first = {
            sequence = { "eggs", "eggs", "eggs", "cannon", "bulwark" },
            cannons = { "heal", "rage", "debuff", "gravity", "repulsor", "nullifier" },
            bulwarks = {
                "impaler_palisade",
                "saw_blade",
                "land_shark",
                "concertina_line",
                "grasping_hedge",
                "wardstone_barrier",
            },
        },
        control = {
            sequence = { "bulwark", "eggs", "cannon", "eggs" },
            cannons = { "gravity", "repulsor", "heal", "debuff", "rage", "nullifier" },
            bulwarks = {
                "grasping_hedge",
                "concertina_line",
                "saw_blade",
                "land_shark",
                "impaler_palisade",
                "wardstone_barrier",
            },
        },
    },
    navigation = {
        project_elevated_stations_to_current_floor = true,
        agent_radius = 2,
        agent_height = 5,
        waypoint_spacing = 5,
        waypoint_distance = 3,
        waypoint_timeout_seconds = 5,
        poll_seconds = 0.1,
        replan_seconds = 1,
    },
    ui = {
        display_order = 110,
        position = { x = 0.5, y = 0.84 },
        size = { x = 0.18, y = 0.055 },
        minimum_size = { x = 150, y = 42 },
        maximum_size = { x = 290, y = 64 },
        off = "AUTOPLAY: OFF",
        on = "STOP AUTOPLAY",
        buy = "AUTOPLAY PASS",
        off_hint = "Online • Waycoins only",
        active_color = { 168, 49, 67 },
        idle_color = { 31, 71, 110 },
        text_color = { 255, 244, 211 },
        corner_scale = 0.2,
        text_min = 10,
        text_max = 17,
    },
    labels = {
        ready = "Ready • Waycoins only",
        collect = "Collecting coins",
        create = "Buying an egg",
        upgrade_base = "Upgrading egg production",
        place = "Supplying the egg line",
        merge = "Combining board eggs",
        cannon = "Improving artillery",
        bulwark = "Improving bulwarks",
        waiting = "Saving for the next upgrade",
        idle = "Waiting for coins or manual unlocks",
        checkpoint = "Waiting for the checkpoint",
        stopped = "Stopped",
        navigation_failed = "Stopped • path blocked",
        pass_required = "Offline Gaming pass required",
        session_ended = "Stopped • bay session ended",
        busy = "Finish the current interaction first",
        error = "Stopped • please try again",
    },
    purchase_menu = {
        title = "AUTOPLAY",
        eyebrow = "OFFLINE GAMING PASS • ONLINE AUTOPLAY",
        description = "Your character collects coins, supplies eggs, and upgrades owned defenses while you are connected.",
        priority_copy = "NO GEMS • NO REBIRTH • NO ASCENSION",
        buy_label_format = "BUY • R$ %d",
        cancel_label = "NOT NOW",
        display_order = 1170,
        minimum_scale = 0.68,
        panel_size = { x = 520, y = 340 },
        palette = {
            scrim = { 0, 0, 0 },
            panel = { 19, 24, 37 },
            header = { 53, 72, 164 },
            accent = { 84, 157, 255 },
            card = { 29, 37, 56 },
            text = { 248, 250, 255 },
            body = { 207, 219, 238 },
            buy = { 45, 185, 92 },
            cancel = { 72, 81, 101 },
        },
    },
}
