-- Tutorial performances reuse the approved Watcher faces and mix. Asset ids live here only.
return {
    enabled = true,
    templates_folder = "TutorialVoiceFaces",
    template_attempts = 3,
    template_retry_seconds = 5,
    faces = {
        angel = { model_asset_id = 90097153593365, label = "Angel", side = "heaven" },
        demon = { model_asset_id = 87113428787101, label = "Demon", side = "hell" },
    },
    audio = {
        group_name = "TutorialVoice",
        load_deadline_seconds = 8,
        tail_seconds = 0.4,
    },
    help_delay_seconds = 12,
    reminder_delay_seconds = 25,
    event_cooldown_seconds = 8,
    reminders = {
        ["tutorial.farm_crystals"] = "tutorial.farm_crystals.reminder",
        ["tutorial.cast_power"] = "tutorial.cast_power.reminder",
    },
    door_failures = {
        pets_equipped = "combat_tutorial.door.pets_equipped",
        hotbar_not_editing = "combat_tutorial.door.hotbar_not_editing",
        hotbar_bound = "combat_tutorial.door.heal_unbound",
        squad_has_role = "combat_tutorial.door.tank_missing",
    },
    door_steps = {
        bind_heal = "combat_tutorial.door.heal_unbound",
        enhance_heal = "combat_tutorial.door.heal_unenhanced",
        battle_brew = "combat_tutorial.door.brew_unused",
        ready_tank = "combat_tutorial.door.tank_missing",
    },
    presentation = {
        display_order = 140,
        -- A small portrait beside the objective stays visible inside rooms and over teaching menus.
        portrait_position = { x = 0.69, y = 0.22 },
        portrait_size = { x = 0.15, y = 0.30 },
        menu_position = { x = 0.66, y = 0.025 },
        menu_size = { x = 0.1, y = 0.12 },
        portrait_max = { x = 156, y = 184 },
        face_height = 0.80,
        label_height = 0.20,
        label_font_size = 15,
        label_color = { 255, 245, 218 },
        stroke_color = { 24, 20, 30 },
        viewport_ambient = { 180, 180, 180 },
        viewport_light = { 255, 240, 218 },
        viewport_light_direction = { -1, -1, -2 },
        camera_distance = 1.65,
        camera_fov = 40,
        face_size = 4,
        fade_seconds = 0.4,
        bob_height = 0.08,
        bob_rate = 1.7,
        turn_degrees = 5,
        speech_turn_degrees = 2,
        loudness_scale = 500,
        -- Outdoor apparition uses a fixed bearing; room/menu/occlusion switches to the portrait.
        world_distance = 12,
        world_side = 8,
        world_height = 5,
        occlusion_scan_seconds = 0.15,
    },
}
