-- Recorded performances: tutorial_voice_assets binds uploads; TutorialNarrator owns playback.
-- Spoken copy is authored here; docs/TUTORIAL_VOICE_SCRIPT.md is the matching recording sheet.
return {
    version = 1,
    status = "runtime_ready",
    recordingManifest = "assets/audio/voices/tutorial/manifest.json",
    -- Playback integration must resolve the already-tuned Merge values, without another gain copy.
    playbackVolumeSource = {
        config = "merge_egg_prototype",
        angel = { "watcher", "voice", "volume" },
        demon = { "watcher", "themes", "hell", "voice", "volume" },
    },
    language = "en",
    sections = {
        {
            id = "homeworld",
            title = "Angel — Farm & Fight introduction",
            speaker = "angel",
            lines = {
                {
                    id = "A25",
                    cue = "tutorial.choose_companion",
                    usage = "conditional",
                    text = "There you are, little light. Let’s choose your first companion. A bunny, a bear, a doggy, or a kitty — who will join you on your adventure?",
                },
                {
                    id = "A01",
                    cue = "tutorial.hatch_first_egg",
                    usage = "main",
                    text = "Your companion could use a friend. Follow the trail to the Earth Egg, and let’s wake one.",
                },
                {
                    id = "A02",
                    cue = "tutorial.farm_crystals",
                    usage = "main",
                    text = "See those crystals? With Farm Near on, your pets will mine beside you. Help them along, and we’ll soon have coins for another friend.",
                },
                {
                    id = "A03",
                    cue = "tutorial.hatch_another",
                    usage = "main",
                    text = "You’ve earned another egg. Shall we see who’s waiting inside? Every new friend gives your little squad more strength.",
                },
                {
                    id = "A04",
                    cue = "tutorial.build_squad",
                    usage = "main",
                    text = "I’ve left a Rainbow Kitty in your inventory. Open Pets, and let’s make room for that bright little spark on your squad.",
                },
                {
                    id = "A05",
                    cue = "tutorial.bind_power",
                    usage = "main",
                    text = "There’s a gift within you, too. It’s called Resonance. Open Edit on your power bar, and give it a place where you can reach it.",
                },
                {
                    id = "A06",
                    cue = "tutorial.cast_power",
                    usage = "main",
                    text = "Now, try Resonance near the crystals. Feel that? Your power helps them break faster and yield a little more.",
                },
                {
                    id = "A07",
                    cue = "tutorial.slot_power",
                    usage = "main",
                    text = "A little Potency will make that gift stronger. Open Powers, and let’s add your new enhancement to Resonance.",
                },
                {
                    id = "A08",
                    cue = "tutorial.first_fight",
                    usage = "main",
                    text = "The Earth cave is a place to practice fighting. Follow the trail when you’re ready. Its instructor has rather more horns than patience.",
                },
                {
                    id = "A09",
                    cue = "tutorial.rally_call",
                    usage = "main",
                    text = "A good leader knows when to call everyone home. Try Rally—the flag on your power bar—and bring your pets back to your side.",
                },
                {
                    id = "A10",
                    cue = "tutorial.completion",
                    usage = "main",
                    text = "Look how far you’ve come. The Ascension Altar is ready for you. Choose your next power, then follow your missions. There’s a whole world waiting.",
                },
            },
        },
        {
            id = "basic",
            title = "Demon — Basic Combat Training",
            speaker = "demon",
            lines = {
                {
                    id = "D01",
                    cue = "combat_tutorial.ready",
                    usage = "main",
                    text = "So. The angel sent me another promising little soul. Choose Enter on that frost door. I’ve found you something suitably unimpressive to fight.",
                },
                {
                    id = "D02",
                    cue = "combat_tutorial.first_fight",
                    usage = "main",
                    text = "There’s your opponent. Get close and let your pets do the fighting. Yes, they do most of the work. Try to look involved.",
                },
                {
                    id = "D03",
                    cue = "combat_tutorial.advance_stage",
                    usage = "main",
                    text = "One training dog defeated. Terrifying. The glowing pillar takes you back to the lobby. We’ll see if that was luck.",
                },
                {
                    id = "D04",
                    cue = "combat_tutorial.battle_brew",
                    usage = "main",
                    text = "Berserk Brew. A little borrowed ferocity for your pets. Take a sip from your power bar. This is the safe room, after all.",
                },
                {
                    id = "D05",
                    cue = "combat_tutorial.ready_brew",
                    usage = "main",
                    text = "Feeling fierce? Enter the arena. Let’s find out whether your pets agree.",
                },
                {
                    id = "D06",
                    cue = "combat_tutorial.brew_fight",
                    usage = "main",
                    text = "Notice the harder hits? That’s the brew. Finish this one before you start taking all the credit.",
                },
                {
                    id = "D07",
                    cue = "combat_tutorial.advance_brew",
                    usage = "main",
                    text = "Better. The pillar will bring you back. Next, we address your squad’s regrettable habit of getting hurt.",
                },
                {
                    id = "D08",
                    cue = "combat_tutorial.bind_heal",
                    usage = "main",
                    text = "You have Heal. How inconvenient for me. Open Edit, put it on your power bar, and finish with Done.",
                },
                {
                    id = "D09",
                    cue = "combat_tutorial.enhance_heal",
                    usage = "main",
                    text = "Let’s make Heal worth using. Open Powers and give it the Healing enhancement I provided. I prefer my opponents properly prepared.",
                },
                {
                    id = "D10",
                    cue = "combat_tutorial.ready_heal",
                    usage = "main",
                    text = "Your healing lesson awaits. Enter the arena—and do pay attention to your pets this time.",
                },
                {
                    id = "D11",
                    cue = "combat_tutorial.select_pet",
                    usage = "main",
                    text = "That yellow health bar belongs to your wounded pet. Select its card. Admiring the problem won’t mend it.",
                },
                {
                    id = "D12",
                    cue = "combat_tutorial.cast_heal",
                    usage = "main",
                    text = "Now use Heal on the pet you selected. Once it recovers, those enemy shields come down. Consider that your warning.",
                },
                {
                    id = "D13",
                    cue = "combat_tutorial.heal_fight",
                    usage = "main",
                    text = "Shields down. Finish both training dogs. The exit pillar is for winners, little hero.",
                },
                {
                    id = "D14",
                    cue = "combat_tutorial.advance_heal",
                    usage = "main",
                    text = "The room is clear. Use the glowing pillar to finish Basic Training. You’ve become slightly less likely to embarrass yourself.",
                },
            },
        },
        {
            id = "advanced_1",
            title = "Demon — Advanced 1: weakening and brew stacking",
            speaker = "demon",
            lines = {
                {
                    id = "D15",
                    cue = "combat_tutorial.ready_weaken",
                    usage = "main",
                    text = "Back for more? How irritatingly diligent. I’ve given you Weakening Vials. Enter the arena, and we’ll spoil someone’s defenses.",
                },
                {
                    id = "D16",
                    cue = "combat_tutorial.select_enemy",
                    usage = "main",
                    text = "Choose the marked enemy’s card. The vial needs a target. Throwing it at your own feet would make a very short lesson.",
                },
                {
                    id = "D17",
                    cue = "combat_tutorial.throw_weaken",
                    usage = "main",
                    text = "Throw the Weakening Vial at your target. Down come the shields. Then you can get on with the unpleasant business of winning.",
                },
                {
                    id = "D18",
                    cue = "combat_tutorial.weaken_fight",
                    usage = "main",
                    text = "Their shields are gone. Defeat both dogs. No, the pillar won’t rescue you from unfinished work.",
                },
                {
                    id = "D19",
                    cue = "combat_tutorial.advance_weaken",
                    usage = "main",
                    text = "You found a weakness and used it. Almost devious. Take the pillar back to the lobby.",
                },
                {
                    id = "D20",
                    cue = "combat_tutorial.stack_brew",
                    usage = "main",
                    text = "More Berserk Brew means bigger hits, not a longer timer. Drink five sips. We’re building a damage meter, not a collection.",
                },
                {
                    id = "D21",
                    cue = "combat_tutorial.ready_stack",
                    usage = "main",
                    text = "There. A proper dose of trouble. Enter the arena while that damage meter has something left to give.",
                },
                {
                    id = "D22",
                    cue = "combat_tutorial.stack_fight",
                    usage = "main",
                    text = "Now watch those hits. Much more convincing. Finish the dog before your borrowed courage wears off.",
                },
                {
                    id = "D23",
                    cue = "combat_tutorial.advance_stack",
                    usage = "main",
                    text = "That was almost efficient. The glowing pillar finishes this course. I suppose you’ll want your reward.",
                },
            },
        },
        {
            id = "advanced_2",
            title = "Demon — Advanced 2: tanks, healers, and the final room",
            speaker = "demon",
            lines = {
                {
                    id = "D24",
                    cue = "combat_tutorial.ready_tank",
                    usage = "main",
                    text = "Let’s put something sturdier between your squad and disaster. Open Pets. One doggy is making room for a bear.",
                },
                {
                    id = "D25",
                    cue = "combat_tutorial.tank_fight",
                    usage = "main",
                    text = "The tank draws attention and takes the punishment. It hits less hard, but your other pets get to keep their dignity—and their health. Finish the fight.",
                },
                {
                    id = "D26",
                    cue = "combat_tutorial.advance_tank",
                    usage = "main",
                    text = "Still standing. How tiresome. Take the pillar back; your next opponents have learned a little trick.",
                },
                {
                    id = "D27",
                    cue = "combat_tutorial.ready_healer",
                    usage = "main",
                    text = "The next pack brought a healer. Leave it alone and it will keep repairing your hard work. Enter when you’ve grasped the problem.",
                },
                {
                    id = "D28",
                    cue = "combat_tutorial.healer_hunt",
                    usage = "main",
                    text = "That green healing mark is your clue. Send your pets after the healer first. I’d rather you didn’t, which should tell you everything.",
                },
                {
                    id = "D29",
                    cue = "combat_tutorial.healer_fight",
                    usage = "main",
                    text = "Healer down. Now finish the rest of the pack. They’re suddenly much less optimistic.",
                },
                {
                    id = "D30",
                    cue = "combat_tutorial.advance_healer",
                    usage = "main",
                    text = "There. No one left to patch them up. Back through the pillar. One last room, and I stop holding your hand.",
                },
                {
                    id = "D31",
                    cue = "combat_tutorial.ready_together",
                    usage = "main",
                    text = "Final room. Two dogs, one healer, and no helpful arrows. You have the tools. Enter when you’re ready to make me regret teaching you.",
                },
                {
                    id = "D32",
                    cue = "combat_tutorial.together_fight",
                    usage = "main",
                    text = "All yours, little hero. Clear the room. Let’s see what you remember when I stop telling you.",
                },
                {
                    id = "D33",
                    cue = "combat_tutorial.advance_together",
                    usage = "main",
                    text = "No arrows, and you still managed it. Deeply inconvenient. Take the glowing pillar and finish your training.",
                },
            },
        },
        {
            id = "completions",
            title = "Demon — Course completion lines",
            speaker = "demon",
            lines = {
                {
                    id = "D34",
                    cue = "combat_courses.basic.completion",
                    usage = "completion",
                    text = "Basic Training, complete. Your pets and powers are ready for the world. Advanced lessons are optional. I’m sure you’ll miss my encouragement.",
                },
                {
                    id = "D35",
                    cue = "combat_courses.advanced_1.completion",
                    usage = "completion",
                    text = "Advanced One, complete. You’ve earned a Double XP token. Use it from your inventory when you want the extra experience. Do try to make it count.",
                },
                {
                    id = "D36",
                    cue = "combat_courses.advanced_2.completion",
                    usage = "completion",
                    text = "All courses complete. There’s a Double Coins token waiting in your inventory. Use it when you’re ready. You’ve become a rather troublesome little hero.",
                },
            },
        },
        {
            id = "angel_help",
            title = "Angel — Short help lines for menu substeps",
            speaker = "angel",
            lines = {
                {
                    id = "A11",
                    cue = "tutorial.build_squad.guide.unequip",
                    usage = "help",
                    text = "Your active squad is full. Let one pet rest in your inventory, and we can welcome the Kitty.",
                },
                {
                    id = "A12",
                    cue = "tutorial.build_squad.guide.pick",
                    usage = "help",
                    text = "There’s your Rainbow Kitty. Choose that little one for the open place on your squad.",
                },
                {
                    id = "A13",
                    cue = "tutorial.build_squad.guide.activate",
                    usage = "help",
                    text = "They’re ready. Choose Activate, and your new squad will join you.",
                },
                {
                    id = "A14",
                    cue = "tutorial.bind_power.choose",
                    usage = "help",
                    text = "Choose Resonance and an open place on your power bar. Put it wherever feels right to you.",
                },
                {
                    id = "A15",
                    cue = "tutorial.bind_power.done",
                    usage = "help",
                    text = "There it is. Choose Done to finish setting your power bar.",
                },
                {
                    id = "A16",
                    cue = "tutorial.slot_power.pick_power",
                    usage = "help",
                    text = "Choose Resonance. That’s the power we’re making stronger.",
                },
                {
                    id = "A17",
                    cue = "tutorial.slot_power.pick_slot",
                    usage = "help",
                    text = "An empty enhancement slot is a little room to grow. Choose one on Resonance.",
                },
                {
                    id = "A18",
                    cue = "tutorial.slot_power.pick_enhancement",
                    usage = "help",
                    text = "Choose Potency. It gives your crystal-boosting pulse a little more strength.",
                },
                {
                    id = "A19",
                    cue = "tutorial.slot_power.apply",
                    usage = "help",
                    text = "Choose Apply, and that extra strength becomes yours.",
                },
                {
                    id = "A20",
                    cue = "tutorial.farm_crystals.reminder",
                    usage = "help",
                    text = "Try a small crystal nearby. Keep Farm Near on, and let your squad earn the coins together.",
                },
                {
                    id = "A21",
                    cue = "tutorial.cast_power.reminder",
                    usage = "help",
                    text = "Bring your squad close to the crystals before you use Resonance. That’s where its gift can help.",
                },
            },
        },
        {
            id = "demon_help",
            title = "Demon — Short help lines for combat menu substeps",
            speaker = "demon",
            lines = {
                {
                    id = "D37",
                    cue = "combat_tutorial.bind_heal.choose",
                    usage = "help",
                    text = "Choose Heal, then give it a place on your power bar. Ideally somewhere you’ll remember when things start biting.",
                },
                {
                    id = "D38",
                    cue = "combat_tutorial.bind_heal.done",
                    usage = "help",
                    text = "Now choose Done. You can admire your arrangement after you survive.",
                },
                {
                    id = "D39",
                    cue = "combat_tutorial.enhance_heal.pick_power",
                    usage = "help",
                    text = "Choose Heal. We’re improving that power, not browsing for something prettier.",
                },
                {
                    id = "D40",
                    cue = "combat_tutorial.enhance_heal.pick_slot",
                    usage = "help",
                    text = "Choose an empty slot on Heal. Even your good intentions need somewhere to go.",
                },
                {
                    id = "D41",
                    cue = "combat_tutorial.enhance_heal.pick_enhancement",
                    usage = "help",
                    text = "Choose Healing. The name is a subtle clue.",
                },
                {
                    id = "D42",
                    cue = "combat_tutorial.enhance_heal.apply",
                    usage = "help",
                    text = "Apply it. A staged enhancement is doing precisely nothing for you.",
                },
                {
                    id = "D43",
                    cue = "combat_tutorial.ready_tank.guide.unequip",
                    usage = "help",
                    text = "Take a doggy off your active squad. The bear needs a place, not an invitation to an already full party.",
                },
                {
                    id = "D44",
                    cue = "combat_tutorial.ready_tank.guide.pick",
                    usage = "help",
                    text = "Choose your strongest bear. The Tank option in Best Pets can find it for you, if counting muscles proves difficult.",
                },
                {
                    id = "D45",
                    cue = "combat_tutorial.ready_tank.guide.activate",
                    usage = "help",
                    text = "Choose Activate. I need the bear in the fight, not posing in your inventory.",
                },
                {
                    id = "D46",
                    cue = "combat_tutorial.ready_tank.guide.close",
                    usage = "help",
                    text = "The bear is on your squad. Close Pets so we can get on with it.",
                },
                {
                    id = "D47",
                    cue = "combat_tutorial.ready_tank.guide.enter",
                    usage = "help",
                    text = "Your tank is ready. Enter the arena and let it earn its place.",
                },
            },
        },
        {
            id = "angel_branches",
            title = "Angel — Handoffs and returning players",
            speaker = "angel",
            lines = {
                {
                    id = "A22",
                    cue = "tutorial.first_fight.handoff",
                    usage = "conditional",
                    text = "Of course. Training will be waiting in Quest whenever you’re ready. You can return to the Earth cave then.",
                },
                {
                    id = "A23",
                    cue = "tutorial.resume",
                    usage = "conditional",
                    text = "Welcome back, little light. We’ll carry on from where you left off. Follow your current lesson when you’re ready.",
                },
                {
                    id = "A24",
                    cue = "tutorial.basic_return",
                    usage = "conditional",
                    text = "Welcome back. I hope he remembered his manners. You’ve learned to look after your squad—and that matters far more than looking fearless.",
                },
            },
        },
        {
            id = "demon_branches",
            title = "Demon — Course selection, interruptions, and blocked doors",
            speaker = "demon",
            lines = {
                {
                    id = "D48",
                    cue = "combat_courses.menu",
                    usage = "conditional",
                    text = "Basic first. Then, if you insist on improving, two advanced courses await. Choose your lesson, little hero.",
                },
                {
                    id = "D49",
                    cue = "combat_courses.locked",
                    usage = "conditional",
                    text = "Finish the earlier course first. Skipping the lesson is not the same as mastering it.",
                },
                {
                    id = "D50",
                    cue = "combat_courses.replay.start",
                    usage = "conditional",
                    text = "A repeat performance? Very well. The practice is yours; the first-time reward stays first-time.",
                },
                {
                    id = "D51",
                    cue = "combat_courses.replay.completion",
                    usage = "conditional",
                    text = "Finished again. No second reward, of course. Surely my company was compensation enough.",
                },
                {
                    id = "D52",
                    cue = "combat_tutorial.leave_confirm",
                    usage = "conditional",
                    text = "Leaving already? Your progress is saved. Come back when you’re ready to disappoint me properly.",
                },
                {
                    id = "D53",
                    cue = "combat_tutorial.resume",
                    usage = "conditional",
                    text = "Back, are you? Your completed lessons still count. We’ll prepare this round again before you enter.",
                },
                {
                    id = "D54",
                    cue = "combat_tutorial.door.pets_equipped",
                    usage = "conditional",
                    text = "Bring at least one pet. This is combat training, not an audition for the role of bait.",
                },
                {
                    id = "D55",
                    cue = "combat_tutorial.door.hotbar_not_editing",
                    usage = "conditional",
                    text = "Choose Done on your power bar first. I prefer my opponents assembled before the fight.",
                },
                {
                    id = "D56",
                    cue = "combat_tutorial.door.heal_unbound",
                    usage = "conditional",
                    text = "Heal belongs on your power bar. Put it there before asking that door to open.",
                },
                {
                    id = "D57",
                    cue = "combat_tutorial.door.heal_unenhanced",
                    usage = "conditional",
                    text = "Add Healing to Heal and apply it. Then we can discuss opening the door.",
                },
                {
                    id = "D58",
                    cue = "combat_tutorial.door.brew_unused",
                    usage = "conditional",
                    text = "The Berserk Brew is for drinking. One sip, little hero. Then you may enter.",
                },
                {
                    id = "D59",
                    cue = "combat_tutorial.door.tank_missing",
                    usage = "conditional",
                    text = "A bear on your active squad, please. Owning a tank is not the same as bringing one.",
                },
                {
                    id = "D60",
                    cue = "combat_tutorial.stack_brew.remaining_4",
                    usage = "conditional",
                    text = "Four more sips. That meter isn’t filling itself.",
                },
                {
                    id = "D61",
                    cue = "combat_tutorial.stack_brew.remaining_3",
                    usage = "conditional",
                    text = "Three more. I admire your commitment to doing this slowly.",
                },
                {
                    id = "D62",
                    cue = "combat_tutorial.stack_brew.remaining_2",
                    usage = "conditional",
                    text = "Two more sips. Even I can see you’re nearly there.",
                },
                {
                    id = "D63",
                    cue = "combat_tutorial.stack_brew.remaining_1",
                    usage = "conditional",
                    text = "One more. Let’s not lose our nerve at the finish.",
                },
                {
                    id = "D64",
                    cue = "combat_tutorial.healer_hunt.lost",
                    usage = "conditional",
                    text = "Your pets have wandered off the healer. Select it again. We were so close to having a strategy.",
                },
            },
        },
    },
}
