#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OUTPUT_PATH = path.join(ROOT, "configs/merge_tier_art.lua");
const PROOF_PATH = path.join(ROOT, "scripts/merge_tier_runtime_manifest.json");
const CANNON_MANIFEST_PATH = path.join(ROOT, "scripts/merge_cannon_model_ids.json");
const BULWARK_MANIFEST_PATH = path.join(ROOT, "scripts/merge_bulwark_model_ids.json");
const BULWARK_PREVIEW_PATH = path.join(ROOT, "scripts/merge_bulwark_preview_ids.json");

const CANNON_FAMILIES = ["heal", "rage", "debuff", "gravity", "repulsor", "nullifier"];
const BULWARK_FAMILIES = [
  "impaler_palisade",
  "concertina_line",
  "land_shark",
  "saw_blade",
  "grasping_hedge",
  "wardstone_barrier",
];

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

function quote(value) {
  return JSON.stringify(String(value));
}

function orderedTiers(entries, label) {
  assert(Array.isArray(entries), `${label}: tier list is missing`);
  const byTier = new Map(entries.map((entry) => [Number(entry.tier), entry]));
  const tiers = [1, 2, 3, 4].map((tier) => byTier.get(tier));
  assert(tiers.every(Boolean), `${label}: expected tiers 1 through 4`);
  return tiers;
}

function validateUnique(entries, field, label) {
  const values = entries.map((entry) => String(entry[field] || ""));
  assert(values.every(Boolean), `${label}: ${field} is missing`);
  assert(new Set(values).size === values.length, `${label}: ${field} values are not distinct`);
}

function collect() {
  const cannonManifest = readJson(CANNON_MANIFEST_PATH);
  const bulwarkManifest = readJson(BULWARK_MANIFEST_PATH);
  const bulwarkPreviews = readJson(BULWARK_PREVIEW_PATH);
  const cannons = {};
  const bulwarks = {};

  for (const family of CANNON_FAMILIES) {
    const tiers = orderedTiers(cannonManifest.families?.[family]?.tiers, `cannon ${family}`);
    cannons[family] = tiers.map((entry) => ({
      tier: Number(entry.tier),
      modelAssetId: String(entry.roblox.modelAssetId),
      meshId: String(entry.roblox.meshId),
      textureId: String(entry.roblox.textureId),
      templateScale: Number(entry.runtime.templateScale),
    }));
    assert(
      cannons[family].every((entry) => entry.templateScale === 1),
      `cannon ${family}: runtime template scale must be 1`,
    );
  }

  for (const family of BULWARK_FAMILIES) {
    const tiers = orderedTiers(bulwarkManifest.families?.[family]?.tiers, `bulwark ${family}`);
    const previews = orderedTiers(bulwarkPreviews.families?.[family], `bulwark preview ${family}`);
    bulwarks[family] = tiers.map((entry, index) => ({
      tier: Number(entry.tier),
      modelAssetId: String(entry.modelAssetId),
      meshId: String(entry.meshId),
      textureId: String(entry.textureId),
      previewDecalId: String(previews[index].decalId),
      previewImageId: String(previews[index].imageId),
    }));
  }

  const cannonEntries = CANNON_FAMILIES.flatMap((family) => cannons[family]);
  const bulwarkEntries = BULWARK_FAMILIES.flatMap((family) => bulwarks[family]);
  for (const field of ["modelAssetId", "meshId", "textureId"]) {
    validateUnique(cannonEntries, field, "all cannon tiers");
    validateUnique(bulwarkEntries, field, "all bulwark tiers");
  }
  validateUnique(bulwarkEntries, "previewDecalId", "all bulwark tier previews");
  validateUnique(bulwarkEntries, "previewImageId", "all bulwark tier previews");

  return { cannons, bulwarks };
}

function renderRegistry(name, families, familyOrder, fields) {
  const lines = [`local ${name} = {`];
  for (const family of familyOrder) {
    lines.push(`    ${family} = {`);
    for (const entry of families[family]) {
      lines.push("        {");
      lines.push(`            tier = ${entry.tier},`);
      for (const field of fields) {
        lines.push(`            ${field} = ${quote(entry[field])},`);
      }
      lines.push("        },");
    }
    lines.push("    },");
  }
  lines.push("}");
  return lines.join("\n");
}

function render(document) {
  return `-- @generated by scripts/sync_merge_tier_art.js; do not hand-edit asset ids.\n-- Model/Mesh/Texture ids come from the proof manifests. Bulwark preview ids come from\n-- scripts/merge_bulwark_preview_ids.json because those cards intentionally use flat art.\n\n${renderRegistry("CANNONS", document.cannons, CANNON_FAMILIES, [
    "modelAssetId",
    "meshId",
    "textureId",
  ])}\n\n${renderRegistry("BULWARKS", document.bulwarks, BULWARK_FAMILIES, [
    "modelAssetId",
    "meshId",
    "textureId",
    "previewDecalId",
    "previewImageId",
  ])}\n\nreturn {\n    cannons = CANNONS,\n    bulwarks = BULWARKS,\n}\n`;
}

function renderProof(document) {
  const flatten = (families, order) =>
    order.flatMap((family) => families[family].map((entry) => ({ family, ...entry })));
  const proof = {
    schemaVersion: 1,
    status: "COMPLETE",
    sourceManifests: [
      "scripts/merge_cannon_model_ids.json",
      "scripts/merge_bulwark_model_ids.json",
      "scripts/merge_bulwark_preview_ids.json",
    ],
    runtimeConfig: "configs/merge_tier_art.lua",
    runtimeConsumers: [
      "src/Shared/Game/MergeTowerProgression.lua",
      "src/Shared/Game/MergeBulwarkProgression.lua",
      "src/Shared/Game/MergeTowerModels.lua",
      "src/Shared/Game/MergeBulwarkModels.lua",
    ],
    counts: {
      cannonFamilies: CANNON_FAMILIES.length,
      cannonTierMappings: CANNON_FAMILIES.length * 4,
      bulwarkFamilies: BULWARK_FAMILIES.length,
      bulwarkTierMappings: BULWARK_FAMILIES.length * 4,
      bulwarkPreviewMappings: BULWARK_FAMILIES.length * 4,
      distinctModelAssets: (CANNON_FAMILIES.length + BULWARK_FAMILIES.length) * 4,
    },
    cannons: flatten(document.cannons, CANNON_FAMILIES),
    bulwarks: flatten(document.bulwarks, BULWARK_FAMILIES),
  };
  return `${JSON.stringify(proof, null, 2)}\n`;
}

function main() {
  const command = process.argv[2] || "check";
  const document = collect();
  const expected = render(document);
  const expectedProof = renderProof(document);
  if (command === "write") {
    fs.writeFileSync(OUTPUT_PATH, expected);
    fs.writeFileSync(PROOF_PATH, expectedProof);
    console.log(`wrote ${path.relative(ROOT, OUTPUT_PATH)}`);
    console.log(`wrote ${path.relative(ROOT, PROOF_PATH)}`);
    return;
  }
  if (command === "check") {
    const current = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, "utf8") : "";
    const currentProof = fs.existsSync(PROOF_PATH) ? fs.readFileSync(PROOF_PATH, "utf8") : "";
    if (current !== expected || currentProof !== expectedProof) {
      throw new Error(
        "Merge tier art registry or proof manifest is stale; run `node scripts/sync_merge_tier_art.js write`.",
      );
    }
    console.log("PASS: Merge tier art registry matches cannon, bulwark, and preview manifests");
    return;
  }
  throw new Error("usage: node scripts/sync_merge_tier_art.js [write|check]");
}

try {
  main();
} catch (error) {
  console.error(error.message || error);
  process.exitCode = 1;
}
